### ISSUE TITLE
Proxy DNS lookups through SOCKS5 possibly broken

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#112]
Sent to me by email:

> When a SOCKS5 proxy is enabled, and if DNS over HTTPS in Firefox is turned on, Firefox does not seem to respect if the proxy server handles DNS or not; it will still query DNS through Cloudflare or NextDNS or whatever it's set to in the browser settings, potentially leaking DNS information. 
> 
> I found this while configuring xxxxxxxxxxxxxx proxy on their servers; using their leak testing tool, it reported I was leaking DNS information. I got the same result while using BrowserLeaks' IP test; even when FoxyProxy was set to using a proxy server, an IP address to Cloudflare was still being queried. When "Enable DNS over HTTPS" in Firerfox's Connection Settings was turned off, neither testing tool showed there were leaks to Cloudflare.
> 
> I don't know whether this is a bug in FoxyProxy, a bug in Firefox, or a limitation in how Firefox handles proxy settings, but it seems as though it could be a privacy/security concern.`

I am guessing this is a Firefox bug, but need to confirm. The WebExtensions API is probably not handling this correctly. The work-around is for FoxyProxy to disable DNS over HTTPS when SOCKS5 is used and proxy DNS is selected.

**Comment by erosman** [comment]
Subsequent to my reply in above topic, I am also enquiring from Mozilla engineers.

**Comment by erosman** [comment]
Is the issue still occurring?

**Comment by erosman** [comment]
Refer to #163
