### ISSUE TITLE
Patterns Mode: When FoxyProxy does not match a URL, it is always loaded through browser's native proxy configuration instead  of DIRECT

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#114]
Sent to me in email

---

If I have my base Firefox proxy settings set up to use a certain proxy (in my case it is SOCKS v.5 proxy with DNS using the proxy) and FoxyProxy Standard (v.7.5.1) configured to work by patterns, a requests which matches a rule (confirmed by FoxyProxy log) for a certain proxy, set to be direct (Proxy Type set to "Direct (no proxy)"), the request seems to be directed via the proxy set up in Firefox, instead of being sent directly to the target.

I've devised a minimum configuration, which shows the issue:

```{
  "litojf1597335017581": {
    "type": 5,
    "color": "#66cc66",
    "title": "Direct connect",
    "active": true,
    "whitePatterns": [
      {
        "title": "*.wtfismyip.com",
        "pattern": "*.wtfismyip.com",
        "type": 1,
        "protocols": 1,
        "active": true
      }
    ],
    "blackPatterns": [],
    "pacURL": "",
    "index": 0
  },
  "mode": "patterns",
  "qtrmdh1597335062950": {
    "type": 3,
    "color": "#cc0000",
    "title": "SOCKS",
    "active": true,
    "address": "localhost",
    "port": 8080,
    "proxyDNS": true,
    "username": "",
    "password": "",
    "whitePatterns": [
      {
        "title": "all URLs",
        "pattern": "*",
        "type": 1,
        "protocols": 1,
        "active": true
      }
    ],
    "blackPatterns": [],
    "pacURL": "",
    "index": 1
  },
  "browserVersion": "79.0",
  "foxyProxyVersion": "7.5.1",
  "foxyProxyEdition": "standard"
}
```
I'm testing with "https://wtfismyip.com/" URL. With this configuration, I expect the request to this URL being direct (with no proxy used), while any other request should be directed at my local SOCKS proxy. This should work regardless of my browser's proxy setup.

In my current network setup, this address is blocked/unreachable directly, but I can access it if the local SOCKS proxy is used, so I can easily check how the request was directed - should work if the SOCKS proxy was used, should be blocked if a direct connection attempt is made for the request.

With the above FoxyProxy configuration in place and the basic proxy configuration of Firefox set to use no proxy, the address indeed is unreachable and becomes reachable if I disable the first FoxyProxy entry, which means, that the first entry is being used, when enabled (the pattern matches). This is an expected/correct behavior.

Unfortunately with the same above configuration of the FoxyProxy (and both entries being left enabled), if my Firefox basic proxy configuration is set to use the local SOCKS proxy, the URL is reached, which indicates, that even if the rule for using direct connection is used, the request is directed according to the basic proxy configuration of the browser. This is not what I would expect as it shows, that the "Proxy Type" option "Direct (no proxy)" is instead "Use browser settings".

**Comment by ericjung** [comment]
Thanks for the detailed bug report.

FoxyProxy returns `'direct' ` when an inclusive/whitelisted pattern does not match. You can see that here:

https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/matcher.js#L57

According to the [Firefox WebExtension Proxy API documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo):


> type string. This describes whether to proxy at all, and if so, what kind of proxy to use. It may take one of the following 
  values:
> 
>  "direct": don't proxy the request. If this value is given, all other properties of this object are ignored.

So this is a Firefox bug. I will open a ticket with Mozilla when I have time, but in the meantime I will change the words from "Direct (no proxy)" to "Direct (use native browser proxy settings)"

FoxyProxy could reset/change native browser proxy settings so they are DIRECT, but I don't want to do that. For one thing, it requires another permission from the user -- private window access.

**Comment by hilari0n** [comment]
> Thanks for the detailed bug report.

No problem.

> FoxyProxy returns `'direct' ` when an inclusive/whitelisted pattern does not match. You can see that here:
> 
> https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/matcher.js#L57

Actually in my case, there is a match to an inclusive/whitelisted pattern, i.e. "*.wtfismyip.com", (so it's rather [this line](https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/matcher.js#L71)), it's just that the pattern is attached to configuration (`litojf1597335017581`) with type 5 (direct).

> So this is a Firefox bug. I will open a ticket with Mozilla when I have time, but in the meantime I will change the words from "Direct (no proxy)" to "Direct (use native browser proxy settings)"

Great. Please post the ticket reference, when available.

> FoxyProxy could reset/change native browser proxy settings so they are DIRECT, but I don't want to do that. For one thing, it requires another permission from the user -- private window access.

That's understandable.

**Comment by erosman** [comment]
That is standard behaviour of the API.

> [proxy.ProxyInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo)
> 
> `"direct"`: don't proxy the request. If this value is given, all other properties of this object are ignored. However, this setting doesn't override any [proxy set by the user](https://support.mozilla.org/en-US/kb/connection-settings-firefox).

`"direct"` refers to the way the Firefox API in FoxyProxy handles the request, not the the way connection is being handled.

**Comment by ericjung** [comment]
@erosman can you remove “Direct (no proxy)” to “ Direct (use native browser proxy settings)” so this is clear?

**Comment by erosman** [comment]
There is no DIRECT option in FoxyProxy v8.0 as discussed earlier.
There is a on/off button to enable/disable a proxy.

For those who used DIRECT as a Global exclude, FoxyProxy v8.0 gas a dedicated Global Exclude option.
