### ISSUE TITLE
disable sync for “currently used profile” setting

### ISSUE THREAD

**Issue by smrqdt** [foxyproxy/firefox-extension#115]
Firefox Sync currently synchronises no only the configured proxies and patterns, but also which profile is currently selected (disabled, by pattern, enable each proxy for all URLs).

It do not think this is useful, as the selected profile is a highly volatile setting and should not be synced, as each device may be in different network conditions and may need different proxy settings. 

It happened to me multiple times that I switched devices an some proxy was selected that was not available on that device (e.g. a SSH SOCKS proxy on localhost) , even though it wasn’t used on the other device for days (there seems to be a lot of sync delay).

I would suggest to exclude the active profile selection from the synchronisation.

**Comment by erosman** [comment]
It is already done in in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

Sync option only synchronises global exclude, proxies & patterns.
**Mode** and **sync** itself are not synced.

That means each set-up can have its own mode and can also choose to sync or not.
