### ISSUE TITLE
Unable to edit proxy because of mysterious "lock"

### ISSUE THREAD

**Issue by tshatrov** [foxyproxy/firefox-extension#117]
![foxyproxy lock](https://user-images.githubusercontent.com/4077725/93381354-34d74880-f869-11ea-8a8c-745a27415b3b.png)
I'm unable to edit one of the proxies that I'm using. I can't add or edit any patterns in this proxy. The only difference from the other proxies that I can edit is the presence of a mysterious green lock in the list of proxies. Clicking on the lock does nothing. ~~How do I "unlock" this proxy and how do I prevent it from being locked again?~~

EDIT: reading the source code, it seems that this icon is turned on when proxy has username and password. However it's still the only proxy in the list that can't be edited. Neither the settings in "Edit" or "Patterns" section are saved. This proxy has dozens of patterns so clearly I was able to edit it before, even quite recently.

EDIT2: Synchronize Settings on/off switch is also not saved. It's currently "On".

EDIT3: After trying and failing to edit this proxy, I decided to create a new proxy and import pattern list into it. However it couldn't save with the imported pattern list! This made me think that something in the pattern list makes the proxy unsavable. Looking through the patterns something caught my eye: Cyrillic text in the title, from the time when the great "quick add pattern" feature existed (it was the best feature ever and really needs to be revived). Example entry:

```
    {
      "active": true,
      "pattern": "bookmeter.com",
      "protocols": 1,
      "title": "Динамический шаблон для Быстрого добавления",
      "type": 1
    },
```

On a whim, I made titles for these patterns blank, and voila: the changes got saved! Could the presence of Cyrillic letters in the title result in pattern list, or even the entire proxy settings, unable to be saved?

Upon further investigation, this hypothesis turned out to be incorrect. I was able to re-add the above title to several patterns just fine. But then, I hit a limit, after which the title couldn't be added anymore. The real problem appears to be that there is *a limit on how large the pattern list can be*. This includes the titles and the patterns. For example at certain point I could remove a letter from a title and add a letter to a pattern, but if I add another letter to a title or pattern, it wouldn't save anymore.

This limit is very low. I only have 79 patterns, but I imagine power users would use far more patterns. Moreover, I couldn't save a patterns list from an existing proxy, so this limit was either larger or didn't exist until some recent update.

**Comment by ericjung** [comment]
The problem is Mozilla's new limitation on size of items that can be synchronized to their servers. Turn off *Synchronize Settings*.

- See [this](https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79) blog post from mozilla.
- See issue #94 
- See issue #95

**Comment by denbkh** [comment]
@ericjung, I have the very similar issue. The sync data limit on the Mozilla's side is 100KB. My exported settings of FoxyProxy is 20 KB. 
I think there should be a possibility to sync my data without problems.

**Comment by ericjung** [comment]
@denbkh i will release a new version shortly that tells you if storage fails due to Mozilla storage limits, rather than failing silently. At least in that case we'll know if your bug is related or something else. But can you confirm that it works with Synchronize Settings disabled?

Please note it is possible that Mozilla's limit is not 100 KB and instead something smaller. I will try to find out.

**Comment by denbkh** [comment]
> But can you confirm that it works with Synchronize Settings disabled?
Yes, if I disable the synchronization then I can edit my patterns without problems.

**Comment by DNACore** [comment]
Now I have the same problem.
I usually use Firefox at work and everything works fine. Synchronize Settings enabled.
But when I install Firefox at home, this problem occurs.
Both have synchronization settings enabled.
Maybe it's a synchronization problem in Firefox itself.

**Comment by ericjung** [comment]
Please disable synchronization and try again. And please let me know if that fixes it. Thank you.

**Comment by DNACore** [comment]
@ericjung Yes， disablle synchronization can fix this.

**Comment by ericjung** [comment]
@DNACore unfortunately, this problem is caused by Mozilla. As I mentioned earlier in this thread:

> The problem is Mozilla's new limitation on size of items that can be synchronized to the Mozilla servers:
> 
> See [this blog post](https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/) from mozilla.
> See issue #94
> See issue #95

So you are trying to store too much data on Mozilla servers. How many patterns and proxies do you have?

**Comment by DNACore** [comment]
@ericjung Only about 150 patterns. If I export patterns and proxies as a json file, it's 21KB.

And more:

Before I installed a new Firefox at home, it was completely normal. Even if the synchronization option is turned on, it can be synchronized normally.
I installed Firefox at home and logged in to my Firefox account. The data of the plug-in can also be synchronized to the newly installed Firefox at home.
After this, the problem appeared.

**Comment by ericjung** [comment]
Perhaps you have other extensions. Those may also use Firefox sync, contributing to your global storage limit.

the bottom line is there is nothing I can do to help you since I do not own or manage the Firefox Synch servers. I recommend you open a bug at bugzilla.mozilla.org.

The next release of FoxyProxy will at least tell you when synchronization storage failed to store your FoxyProxy info. That’sall I can offer.

good luck.
