### ISSUE TITLE
Not able to add new whitelist on Firefox 81.0 on Mac

### ISSUE THREAD

**Issue by dove-young** [foxyproxy/firefox-extension#118]
I am using FoxyProxy Standard 7.5.1 on Firefox 81.0 on Mac.  

I have already have several urls in white list for a couple of years. But when I add a new url pattern to whitelist to a proxy, and click save, it just disappears when I come back and check it again.   

I tried to export patterns to a JSON file, and add new whitelist pattern in the JSON file, and import setting from there.  I can see the new pattern after import, but when I click Save button, it just disappears. 

But the same action works on Firefox 78.3.0 esr on Mac

**Comment by ericjung** [comment]
It's probably issue #110.
Can you turn off Synchronize Settings on the main FoxyProxy window and try again?

**Comment by ericjung** [comment]
Hello, any reply? Did disabling 'Synchronize Settings' fix the problem?

**Comment by zouri** [comment]
I had the same problem and it was solved by turning off sync

**Comment by ericjung** [comment]
Yes, this is indeed a sync problem. Turn it off. I will add better error messaging.

**Comment by erosman** [comment]
The issue should be sorted in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).
