### ISSUE TITLE
Make better UI for Fenix (Firefox Nightly)

### ISSUE THREAD

**Issue by xmha97** [foxyproxy/firefox-extension#119]
Hi,
Fenix (Firefox Nightly) now support "FoxyProxy Standard"
Please make better UI for Fenix (Firefox Nightly)
![Fenix](https://user-images.githubusercontent.com/23485114/95751465-82e63d00-0cab-11eb-967e-f49d6151c83e.jpg)

**Comment by xmha97** [comment]
Like Dark Reader:
On Fenix:
![Screenshot_2020-10-12-16-57-06-745_org mozilla fenix](https://user-images.githubusercontent.com/23485114/95752096-61d21c00-0cac-11eb-94df-ef606a043557.jpg)
On PC:
![image](https://user-images.githubusercontent.com/23485114/95752104-6696d000-0cac-11eb-8b3a-4e0ccfd5c145.png)

**Comment by One010101** [comment]
I need it, too

**Comment by erosman** [comment]
UI is updated in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (currently in beta).
