### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#120]
From email:

> The shortcut keys for the on/off of the proxy, and switching between proxies.

**Comment by erosman** [comment]
Keyboard Shortcuts for specific actions are easy to do. Nowadays, it is best to set up a basic shortcuts and let users change it via Firefox interface.

Keyboard Shortcuts to switch between proxies that are not known (added by user) is more difficult.

Please also note that Keyboard Shortcuts are very congested and there are not many free ones available (mostly 3+ key combinations). Firefox overrides those having conflict with Firefox Keyboard Shortcuts. Furthermore, web sites often have code that intercepts Keyboard Shortcuts. 

In case of conflict with other extension, the first one loaded gets it.

**Comment by ericjung** [comment]
@erosman thanks. To start, I will just use on/off shortcut. I am guessing [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) is the relevant syntax?

**Comment by erosman** [comment]
> I am guessing this is the relevant syntax?

Yes... but in practice, a bit of tweaking is required.

Give me a bit of time and I will add the basic framework it for you and then you can take it from there.

Also prepare a bit of explanation/help .... here is a copy of mine:

  <h4>Keyboard Shortcut</h4>
  <p>Setting is available directly from Firefox (66+).</p>
  
  <blockquote><b>Manage extension shortcuts in Firefox</b><br><br>
  
  You can now change your extensions' keyboard shortcuts on the add-ons page.
  
  <ol>
    <li>Click the menu button <code>&#x2630</code>;, click <code>Add-ons</code> and select <code>Extensions</code>.</li>
    <li>Click the Tools for all add-ons cogwheel.</li>
    <li>Click <code>Manage Extension Shortcuts</code> in the menu.</li>
    <li>You will see the shortcut options (if available) for your installed add-ons.</li>
  </ol>
  
  <cite><a href="https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox" target="_blank">Manage extension shortcuts in Firefox</a></cite>
  </blockquote>

**Comment by sathishshan** [comment]
@erosman Hi, The customized shortcut keys would be better, for anyone's personalized usage.

**Comment by erosman** [comment]
Basic framework code for keyboard shortcuts is added which requires  testing and discussion on further development
No keyboard sets has been assigned and it is left to users to choose via Firefox (not FoxyProxy) interface as mentioned previously

**Comment by ericjung** [comment]
@erosman where is the code for that? Did you push it to git?

**Comment by erosman** [comment]
> where is the code for that? Did you push it to git?

Yes .... long time ago (17 Oct 2020)

https://github.com/foxyproxy/firefox-extension/commits?author=erosman

**Comment by ericjung** [comment]
@erosman the commits from 17 Oct 2020 are only manifest.json changes. You added 12 lines then removed the same 12 lines -- so overall, no changes. What happened?

**Comment by erosman** [comment]
At first I added them to the master, then removed them from the master and added them to branch 7.5.2

https://github.com/foxyproxy/firefox-extension/commit/ab7c946f8c6daeefa86afb5b85e82583ffc7a27a#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26
https://github.com/foxyproxy/firefox-extension/commit/29eadb0318f7fbece2d919c28608a7bf099e382b#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

e.g.
https://github.com/foxyproxy/firefox-extension/blob/29eadb0318f7fbece2d919c28608a7bf099e382b/src/manifest.json#L48-L58

https://github.com/foxyproxy/firefox-extension/blob/29eadb0318f7fbece2d919c28608a7bf099e382b/src/scripts/background.js#L63-L71

**Comment by erosman** [comment]
Regarding [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension):


1. By design, keyboard shortcuts aim at actions that are performed regularly such as copy/paste etc. How frequently users change mode?
2. Keyboard shortcuts are often congested by the browser and other extension resulting in possibly a 3-key combination. How convenient is that comparing to toolbar popup?
3. What actions keyboard shortcut is going to perform? Set pattern or disable action is possible. What else?

**Comment by erosman** [comment]
Added Keyboard Shortcut feature in v8.1
