### ISSUE TITLE
No Basic Auth - 

### ISSUE THREAD

**Issue by P4nr4g3** [foxyproxy/firefox-extension#121]
I have seen that this issue has occurred a couple of time.

Was there a fix for this.
Installing both Standard and Basic has the same affect.
Installing manually also does not work.
I have tested the site with the proxy settings in Firefox itself and this works.
Removing the plugin is the only way to get the system proxy to work. Whilst the plugin is installed it does not.
Settings exported below:

{
  "logging": {
    "size": 100,
    "active": true
  },
  "mode": "disabled",
  "myvr6m1594990184540": {
    "type": 3,
    "color": "#ff00cc",
    "title": "Proxychains",
    "active": true,
    "address": "127.0.0.1",
    "port": 8081,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "blackPatterns": [],
    "whitePatterns": [],
    "pacURL": "",
    "index": 9007199254740989
  },
  "qnybvm1592325905101": {
    "type": 1,
    "color": "#cc5800",
    "title": "BURP Intercept",
    "active": true,
    "address": "127.0.0.1",
    "port": 8080,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "blackPatterns": [],
    "whitePatterns": [],
    "pacURL": "",
    "index": 9007199254740990
  },
  "yhojbv1604070851770": {
    "type": 1,
    "color": "#00aacc",
    "title": "Squid HTTP Proxy",
    "active": true,
    "address": "10.10.10.21",
    "port": 3128,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "blackPatterns": [],
    "whitePatterns": [],
    "pacURL": "",
    "index": 9007199254740988
  },
  "browserVersion": "78.3.0",
  "foxyProxyVersion": "7.5.1",
  "foxyProxyEdition": "basic",
  "sync": true
}

**Comment by ericjung** [comment]
hello,

What exactly is the problem? Username/password are both empty in the settings you provided. Basic Auth is not going to work when those are empty.

**Comment by P4nr4g3** [comment]
It was more wanting the box to pop up and prompt if the credentials were not in those boxes. Is the basic authentication prompt box not an options with foxyproxy?

**Comment by erosman** [comment]
It should not be an issue in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

If user/pass are not saved, the authentication should be taken over by the browser.
