### ISSUE TITLE
Wrong configuration displayed in "overview" tab

### ISSUE THREAD

**Issue by liar666** [foxyproxy/firefox-extension#123]
Hi,

Thanks for the extension, it's very useful. Just a small display bug that have noticed:

I've configured 3 proxys (cf. attached picture):
- (green) => socks proxy
- (blue) Home => no proxy
- (orange) U => manually set proxy

As can be seen in the picture, in the "overview" tab, the Home proxy (no proxy) is displayed as having the same configuraition as the proxy belong, which is totally wrong (1. Home is set to "No Proxy" / 2. Home does not even have an old setting with a proxy which would then have been switched to "No Proxy" - thus none of the "Proxy" fields are filed for Home setting)

![foxy_bug](https://user-images.githubusercontent.com/3216927/99938599-6d633900-2d68-11eb-9130-c1055730a6f7.png)

FYI:
Edition: FoxyProxy Standard
Version: 7.5.1

**Comment by ericjung** [comment]
Hello,

Thanks for writing. I'm having a difficult time understanding the problem. can you please export the settings and paste them here (you can remove any sensitive info before pasting).

thank you,
eric

**Comment by liar666** [comment]
Hi,

Sorry my English is probably too bad.

The problem is simple: if you look at the picture in my previous message, the blue entry (Home) is a "Direct Proxy" it should not display any url  (part starting with "cache.univ..." is erroneous).

Steps to reproduce:
1. Create a new entry / proxy setup.
2. Configure it as follows:
   - Type:  HTTP proxy
   - ip: plop.com
   - port 3128
   - no user/pass
3. Save it
4. Edit it
5. Change "Type" to "No Proxy"
6. Save it
In the panel that lists your proxies, you''ll get same error as shown in picture: Home will be listed with "plop.com" as a proxy, whereas it is now a "No Proxy" entry.

See attached export with minimal working example
[FoxyProxy Standard_2020-12-13.json.txt](https://github.com/foxyproxy/firefox-extension/files/5684372/FoxyProxy.Standard_2020-12-13.json.txt)

**Comment by ericjung** [comment]
Thank you. I understand the problem and will fix it.

**Comment by erosman** [comment]
There is no DIRECT option in FoxyProxy v8.0.
There is a on/off button to enable/disable a proxy.

For those who used DIRECT as a Global exclude, [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) has a dedicated Global Exclude option.
