### ISSUE TITLE
Improvement request: configure/use/import global username/password for multiple servers

### ISSUE THREAD

**Issue by rafi-d** [foxyproxy/firefox-extension#124]
Hi,
There is a list of  servers that I like to import. This list is maintained by a third part , that  I have an account with (single/same username/ & password of cause). The list does NOT include my username/password.

Every time when I am trying to import it, I need to edit each and every one of the servers, adding my login information.
Can you please add a global setting for username password, and a checkbox per server to optionally use that global login info?

In the import function - also add an option to use that global login info for every server imported (maybe by a checkbox, or some default settings in the format. Adding an option to import from a url (file) canbe helpful too. 

It's seems like a small addition that can be very useful to many.

Thanks!

Rafi

**Comment by ericjung** [comment]
Wouldn't it be easier for either:

1. Your proxy provider to publish the list to you including username and password?  For example:
`192.1681.1.2:666:johnConnor:hunterKiller2`
(this is commonly done)
see https://github.com/foxyproxy/firefox-extension/wiki/Import-Proxy-List

2. If the provider won't do that, open the list in a text editor. use find/replace to insert you username/password on each line before importing into FoxyProxy. For example, if the list is this format:

`192.168.0.89:3128
192.168.0.90:2112
192.168.0.91:13371`

Find all `(.+)` and replace with `$1:myUsername:myPassword`

Tested in VisualCode 1.51.1, Atom 1.52.0, Sublime Text 3.2.2. You can optionally use `^(.+)$` but it is not necessary in the text editors I tested.

Be sure to use turn on regular expression find in your tool.

**Comment by rafi-d** [comment]
Hi,
I am aware that I *can* edit any list. But no, it will not be easier... :) If there is a single login for all, it will be much easier to have a global setting for it to fit all in some "general" setting location, plus provision the servers to use it as default if  one was defined ( none empty).



And providers cannot input passwords, since they do not know them, for security reasons (as you can surely imagine).
