### ISSUE TITLE
FoxyProxy Basic is wrongly displaying zh-CN name

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [foxyproxy/firefox-extension#127]
FoxyProxy Basic should be named “FoxyProxy 基础版” in zh-CN locale. However after I installed this extension just now, I got a surprise on the Add-on Manager:
![Screenshot 1](https://user-images.githubusercontent.com/10364351/101236930-e8850180-370f-11eb-9bc1-c42de25bf716.PNG)
Comparing to [source code](https://github.com/foxyproxy/firefox-extension/blob/master/src/_locales/zh_CN/messages.json):
![Screenshot 2](https://user-images.githubusercontent.com/10364351/101236972-1ff3ae00-3710-11eb-8e0a-06f682db8b2c.PNG)

**Comment by ericjung** [comment]
OK -- I think I see the problem.

https://github.com/foxyproxy/firefox-extension/blob/master/src/manifest.json#L4 should be *extensionNameBasic*  when building FoxyProxy Basic. https://github.com/foxyproxy/firefox-extension/blob/master/src/_locales/zh_CN/messages.json#L5

Do you agree?

**Comment by erosman** [comment]
My personal view has always been to treat extension name as Trade Mark, and thus never translate the extension name.
Additionally, [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) is a unified FoxyProxy extension (no more Standard/Basic or Firefox/Chrome versions).
