### ISSUE TITLE
Show long proxy names

### ISSUE THREAD

**Issue by hoxu** [foxyproxy/firefox-extension#131]
Options view shows only 9 first characters, and icon popup menu shows 18 first characters for each proxy. The latter ends in "(for all URLs)", which could be indicated in a way that leaves more space for the proxy name.

It would be good to be able to view longer proxy names, and/or be able to see the full proxy name as a tooltip in both views.

**Comment by ericjung** [comment]
Thanks for the good suggestion. I will add it.

**Comment by erosman** [comment]
Done for [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).
