### ISSUE TITLE
Maximun pattern entries reached.

### ISSUE THREAD

**Issue by newboydj169** [foxyproxy/firefox-extension#133]
[FoxyProxy Standard_2021-01-28.zip](https://github.com/foxyproxy/firefox-extension/files/5885240/FoxyProxy.Standard_2021-01-28.zip)

I cannot add more pattern to foxyproxy. unless delete some entries.
I have tryed export the json and direct edit json and import go firefox again, but this time I cannot import proxy setting unless i removed exceeded entries.(I promiss I have respect to the json format)
Would you mind to have a check?
I also attached my setting json file.
thank you in advance.

**Comment by ericjung** [comment]
hello,

I am sorry. It is a UI quirk, but not broken. Please see screenshots on what to do :

![133-1](https://user-images.githubusercontent.com/5875610/106328414-05840f80-623d-11eb-8931-c7922e5ecb71.jpg)
![133-2](https://user-images.githubusercontent.com/5875610/106328429-0cab1d80-623d-11eb-8474-952a0dc459d3.jpg)

**Comment by newboydj169** [comment]
that's it, thank you so much.

**Comment by newboydj169** [comment]
Eric,
Actually I did a test by following your instrocution， it's works only when I  disable sync.
