### ISSUE TITLE
solution only works when turn off sync.

### ISSUE THREAD

**Issue by newboydj169** [foxyproxy/firefox-extension#134]
hello,

thanks for the solution. but it's only works when turn off sync.

 

> I am sorry. It is a UI quirk, but not broken. Please see screenshots on what to do :

> ![133-1](https://user-images.githubusercontent.com/5875610/106328414-05840f80-623d-11eb-8931-c7922e5ecb71.jpg)

> ![133-2](https://user-images.githubusercontent.com/5875610/106328429-0cab1d80-623d-11eb-8474-952a0dc459d3.jpg)

_Originally posted by @ericjung in https://github.com/foxyproxy/firefox-extension/issues/133#issuecomment-770056123_

>

**Comment by Player701** [comment]
OP is saying there is a limit on the number of patterns that can be added when the "Synchronize Settings" switch is turned on. I have the same issue - with sync on, there seems to be a hard limit of 90 or so patterns that can be present in the list at the same time. This limitation might be enforced by Firefox itself, although it appears to be rather restrictive by today's standards. If this is indeed true, then it's really bad UX when a newly-added pattern exceeding the limit simply disappears into thin air without any kind of error message. Some sort of user-friendly handling for this error would be really nice to have.

**Comment by ericjung** [comment]
Yes, Firefox limits the amount of data you can sync to something like 100 on. I’m not sure of the exact amount. But it are right. The UI should warn you about it and it doesn’t. We are fixing this is FoxyProxy version 8.

**Comment by erosman** [comment]
Storage quotas for sync data

- Maximum total size 102,400 bytes (100KB)
- Maximum item size 8,192 bytes (8KB)
- Maximum number of items 512

**Comment by erosman** [comment]
We are working on the next update of [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) and although the sync limit by Firefox cant be overcome, it should not cause any problems with the operation of FoxyProxy.
