### ISSUE TITLE
Expand title column in the FoxyProxy Options window 

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#135]
From email:

I am using Dynamic socks proxy settings, and here is how my proxy looks like.

The title/description is too short, so I need to go to edit mode for each one, to find one I would like to edit.

![Foxy_Proxy_screenshot01](https://user-images.githubusercontent.com/5875610/107415224-5662f600-6ad0-11eb-9650-1e178e16f3eb.png)

Firefox version used 84.0.2 (64-bit)

I would like to have "localhost" located from the right side, and the rest of the space allocate for title/description.

Thank you in advance!

**Comment by erosman** [comment]
UI is redesigned in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).
