### ISSUE TITLE
Proxy in Incognito / Private Browsing Mode

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#136]
From email:

> I'd like to use a proxy for everything I visit using an Incognito window.

"Use XXX For All URLs" is not good because:

1)  Then everything in every browser window is going through that proxy, including my gmail and every open page that updates itself.  If I'm going to Incognito & proxy for privacy reasons, it'd be best of all those other websites couldn't correlate me to that VPN exit node at that date and time.

2)  If I find a link in my regular browsing and use "Open Link in New Private Window", it's too late.  I have to plan ahead to do the manual switch.

**Comment by erosman** [comment]
Options are:

- Using patterns instead of for all (personally, I regularly switch between pattern & all)
- If user does not want proxy in Private Browsing at all, it can be disabled from Firefox addon options (although not tested)
   **about:addons -> FoxyProxy -> Run in Private Windows -> Don’t Allow**

**Comment by ericjung** [comment]
@erosman is it possible to detect Private Browing mode at runtime?

**Comment by erosman** [comment]
[proxy.onRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/RequestDetails) has **incognito** boolean.

https://github.com/foxyproxy/firefox-extension/blob/16992e67fe8b9dd27268732cb3126aa1a5ecd56e/src/scripts/background.js#L140-L142

Therefore ....

```js
function proxyRequest(requestInfo) {
  // check incognito
  if (requestInfo.incognito) { /* process */ }
  
  return findProxyMatch(requestInfo.url, activeSettings);
}
```

User preferences would be needed for:

- proxy for normal & incognito (as FP runs now)
- proxy for normal but not incognito (disabled for incognito)
- not for normal but for incognito (disabled for normal)
- same patterns for normal & incognito
- different patterns for normal & incognito

**Comment by mipek** [comment]
I wanted something like this myself and implemented it by adding a simple flag that specifies whether or not a particular proxy configuration can be used in incognito mode or not. This means you can have two separate sets of proxies (one set for regular browsing and one for incognito browsing). In incognito browsing only proxies that have this flag are allowed to be used.

The downside is that you need to have at least one proxy configured for incognito mode otherwise it deliberately fails to establish a connection (which may be a good thing depending on the user).

If this sounds okay I'm happy to provide a pull request.

**Comment by erosman** [comment]
Note: incognito separation of proxy is not possible in Chrome.

**Comment by pmarks-net** [comment]
> incognito separation of proxy is not possible in Chrome.

It works fine in my extension: https://github.com/pmarks-net/incognito-proxy

**Comment by erosman** [comment]
> > incognito separation of proxy is not possible in Chrome.
> 
> It works fine in my extension: https://github.com/pmarks-net/incognito-proxy

That is a bit different.

The question in FoxyProxy is how to handle include/exclude patterns and user options, similar to the answer given in #194 regarding containers.

**Comment by ghost** [comment]
> Options are:
> 
>     * Using patterns instead of for all (personally, I regularly switch between pattern & all)
> 
>     * If user does not want proxy in Private Browsing at all, it can be disabled from Firefox addon options (although not tested)
>       **about:addons -> FoxyProxy -> Run in Private Windows -> Don’t Allow**

Perhaps a simple dropdown box to enable/disable the pattern in normal or private tabs?
Also, any news on this feature?

**Comment by erosman** [comment]
The next update of FoxyProxy has a unified code for Firefox & Chrome.
In Chrome, proxy can apply to all, or only to incognito windows.

### [chrome.proxy: Examples](https://developer.chrome.com/docs/extensions/reference/proxy/#examples)

> The settings apply to regular and incognito windows, as incognito windows inherit settings from regular windows. Please also consult the [Types API](https://developer.chrome.com/docs/extensions/types#ChromeSetting) documentation.


### [Chrome settings](https://developer.chrome.com/docs/extensions/reference/types/#ChromeSetting)

> **regular**
> Settings set in the regular scope apply to regular browser windows and are inherited by incognito windows if they are not overwritten. 
> 
> **incognito_persistent**
> Settings set in the incognito_persistent scope apply only to incognito windows.

**Comment by erosman** [comment]
> Perhaps a simple dropdown box to enable/disable the pattern in normal or private tabs?
> Also, any news on this feature?

Added Tab Proxy feature (Firefox only) in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

See also: #125

**Comment by erosman** [comment]
Follow on: [Incognito & Container Support](https://github.com/foxyproxy/browser-extension/issues/33)

**Comment by pmarks-net** [comment]
Could you clarify how to configure FoxyProxy so that all private browsing tabs use a proxy?

I would like to add the instructions to https://github.com/pmarks-net/incognito-proxy

**Comment by erosman** [comment]
> Could you clarify how to configure FoxyProxy so that all private browsing tabs use a proxy?

The feature is not finalised yet. It will be available in future release of FoxyProxy.

**Comment by pmarks-net** [comment]
Ah, so https://github.com/foxyproxy/browser-extension/issues/33 is a replacement for this bug.

**Comment by ericjung** [comment]
> Ah, so [foxyproxy/browser-extension#33](https://github.com/foxyproxy/browser-extension/issues/33) is a replacement for this bug.

Yes
