### ISSUE TITLE
does not connect to the first

### ISSUE THREAD

**Issue by gitanopro** [foxyproxy/firefox-extension#139]
With the proxy already activated, when it is closed and opened, the IP of the browser is the original one and not that of the configured proxy.  Touching a bit and changing the connection and reconnecting, the proxy works again, but if the process of closing and opening is repeated, the IP remains the local or original one.

**Comment by ericjung** [comment]
I am sorry, but I cannot reproduce this bug. Please provide your foxyproxy.json file (export settings). You can remove username/password in that file if they exist.

Thank you,
eric

**Comment by ericjung** [comment]
Closing; no response from @gitanopro.
