### ISSUE TITLE
Improve UI for disabled mode use case

### ISSUE THREAD

**Issue by shmerl** [foxyproxy/firefox-extension#14]
Currently, FoxyProxy add-on uses red striked out icon, when it's disabled (in Firefox toolbar). It would improve general appearance, if instead it would simply gray out the icon (like for example uBlock Origin does). It fits better with modern desktop design (like in KDE), where icons are often using neutral tones, and bright red usually indicates something that requires attention.

**Comment by ericjung** [comment]
Thanks for the good suggestion. Would you be willing to edit the existing icon so it's gray? You can find it [here](https://github.com/foxyproxy/firefox-extension/blob/master/src/images/48x48.svg).

**Comment by shmerl** [comment]
Try this: 
[48x48_disabled.zip](https://github.com/foxyproxy/firefox-extension/files/3390181/48x48_disabled.zip)

**Comment by shmerl** [comment]
Alternatively, you can use CSS filters for grayscale that should work on existing icon I think.

**Comment by ericjung** [comment]
> Alternatively, you can use CSS filters for grayscale that should work on existing icon I think.

we weren't able to get this to work. It seems to be a problem only with:

1. firefox addons
2. browser_action icon updates (toolbar icon) to SVG-based icons.
3. Probably related to this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1406473) I opened 2017-10-06

So we now have a separate SVG icon with greyscale.

**Comment by shmerl** [comment]
Can you push a new release with it please? Thanks!

**Comment by ericjung** [comment]
Hi, unfortunately, I can't push a release to hundreds of thousands of users just to update an icon. The releases must be more substantial because every update opens the About page showing release notes, which some people find annoying. Having said, we are working a huge re-write of the addon and expect it to be released within 30 days. The re-write does not change the basic UI, although there are definitely UI improvements, but most of the changes are under-the-hood.

**Comment by ericjung** [comment]
I'm not going to add this for now. All the grayscale images I created were too blurry; the resulting icon is not distinguishable as FoxyProxy. I think the reason is the existing foxhead icon (which is what I used to create the grayscale version) is just too detailed. I need a graphic designer to make a grayscale version.

**Comment by shmerl** [comment]
At least may be provide an option for such icon for those who want to use it, until you make a better one. I took a look at it - for me it's a definitive improvement.

**Comment by shmerl** [comment]
Just an idea, but what about simplifying the original icon? It's indeed to detailed and not very suitable for small use case, like here:

![image](https://user-images.githubusercontent.com/310927/66179640-c8534180-e637-11e9-9695-479b61e327ef.png)

I'd say, even  current disabled colored icon is hard to recognize, unless you know what it is already.

**Comment by ericjung** [comment]
> what about simplifying the original icon?

I'm open to that. But I'm not a graphic artist and can't do this myself.

**Comment by jespersh** [comment]
Hi Eric!

Thought I'd drop in and say that the original reason I didn't go for a grey icon when disabled, was that if someone actually picked grey for the icon, then they wouldn't be able to tell disabled state apart from enabled proxy state

**Comment by ericjung** [comment]
Thanks, @jespersh. Icon color can still be customized, so that confusion is still a possibility, but at this point I would say “user beware” and give the flexibility for a user to confuse himself 😀

**Comment by LinuxOnTheDesktop** [comment]
I think the colour should be user-selectable. For, for my use case, even a red icon is too little warning; I would prefer a large banner or something of that sort.

**Comment by erosman** [comment]
[FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) has a normal icon when enabled and a greyscale icon when disabled.
