### ISSUE TITLE
Consider TLS 1.3 support and/or forward secrecy with better TLS 1.2 ciphers

### ISSUE THREAD

**Issue by hardhub** [foxyproxy/firefox-extension#140]
I have tried all possible ciphers from TLS 1.2 suite and nothing works.

I am about connection to proxy with _Proxy Type_ `HTTPS/SSL`.

**Comment by hardhub** [comment]
I think I have found more information.

The following TLS 1.2 ciphers are **not supported**:
```
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

**Comment by hardhub** [comment]
It looks that FoxyProxy supports only RSA as key exchange.

And most secure of available ciphers will be `TLS_RSA_WITH_AES_128_GCM_SHA256` and `TLS_RSA_WITH_AES_256_GCM_SHA384`

Though both do not support Forward Secrecy and SSL Lab downgrades rank of TLS with such ciphers to B.

But I think they are still secure to use. Though let's rename issue...

**Comment by ericjung** [comment]
FoxyProxy defers all connection handshakes to Firefox and the proxy server you are using. None of this relates to FoxyProxy itself.

**Comment by hardhub** [comment]
> 
> 
> FoxyProxy defers all connection handshakes to Firefox and the proxy server you are using. None of this relates to FoxyProxy itself.

@ericjung Unfortunately I afraid it is wrong. Have you tested it before claim that?

**Comment by ericjung** [comment]
> Have you tested it before claim that?

There is no proxy handshake code in FoxyProxy. So if it breaks in your tests, you are probably not testing FoxyProxy. Please disable FoxyProxy then try your tests with Firefox natively (no browser add-on to manage proxies):

![image](https://user-images.githubusercontent.com/5875610/112773531-984dea00-8ff3-11eb-8634-bc02a2fd4b9f.png)

**Comment by hardhub** [comment]
OK, clear. I will check all once again.
