### ISSUE TITLE
Option to trust/distrust proxy certificate when turning on/off proxies

### ISSUE THREAD

**Issue by FalcoGer** [foxyproxy/firefox-extension#142]
I want to use foxyproxy to connect to my localhost intercepting proxy/proxies (such as OWASP ZAP, BurpSuite, mitmproxy, etc).

For those proxies to be able to do their job (intercepting requests and letting me fiddle with them) they require a CA certificate to be trusted. You can add those certificates just fine in firefox, however they present a security vulnerability as anyone who gets their hands on those certificates can now easily fake websites for me by signing them with that root cert.

Most of the time I do not want to use those proxies, so having the root ca trusted is a potential vulnerability when just surfing the internet. But sometimes I do need them.

Is it possible for foxyproxy to enable or disable/add or remove specific certificates when you turn on the proxy? That would solve the issue.

**Comment by erosman** [comment]
Certificates are handled by Firefox and extensions have no control over them.
