### ISSUE TITLE
For a brief moment when starting the browser foxy proxy is not working

### ISSUE THREAD

**Issue by gitanopro** [foxyproxy/firefox-extension#143]
If I install foxy proxy in my firefox browser and start the profile through command line (run) and open a page that tells me the ip I have, the page shows the real ip, not the proxy ip, this is because for a brief time when starting firefox with run, foxy proxy is not working. This may be a problem, for me it is, please fix it

**Comment by erosman** [comment]
Unfortunately, that is normal.

- Firefox starts
  At this time extensions are not loaded but Firefox starts to make net connections for its own functions
- Firefox starts to load extensions
  Extensions get loaded one by one and it can take a few seconds to minutes (especially after a browser upgrade) for all extensions to load
- Extensions start to function
  Extensions need to get their own data e.g. user/pass, storage patterns, remote data before they are fully operational
  

During the time it takes for extensions to be fully functional, Firefox continues to operate and in this case, connections go through without a proxy, or can go through a proxy but extension hasn't got the user/pass from storage yet to connect to the proxy.

To ensure proper operation, it is best to wait for the extensions to complete loading before making net connecitons e.g. openning webpages.
