### ISSUE TITLE
result.hostData is undefined

### ISSUE THREAD

**Issue by ThomasCr** [foxyproxy/firefox-extension#148]
When I use FoxyProxy, my Internet always hangs. 

Also when I switch to the DIRECT Connect "Proxy" without "proxys based on their pre-defined patterns and prios.." setting.

(my computer has also direct access, without proxy)

On our corporate proxy, we use auth.... dont know if it matters. But I also don't get a auth dialog.

On Firefox Java Console I get this message:

```result.hostData is undefined 2 background.js:254
    getAuth moz-extension://617e789a-befc-4818-b30d-ced864cac87f/scripts/background.js:254
    apply self-hosted:2707
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    applySafe resource://gre/modules/ExtensionCommon.jsm:599
    applySafe self-hosted:1173
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:829
```
When I disable the extension I am able to browse the Internet again.

FF is current Version from Linux Mint:
```
$ apt policy firefox
firefox:
  Installiert:           88.0.1+linuxmint1+ulyssa
  Installationskandidat: 88.0.1+linuxmint1+ulyssa
  Versionstabelle:
 *** 88.0.1+linuxmint1+ulyssa 700
        700 http://packages.linuxmint.com ulyssa/upstream amd64 Packages
        100 /var/lib/dpkg/status
     88.0.1+build1-0ubuntu0.20.04.2 500
        500 http://de.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     75.0+build3-0ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by ThomasCr** [comment]
![grafik](https://user-images.githubusercontent.com/226670/118988839-d62b1700-b981-11eb-9722-a92f1bcf44d1.png)

**Comment by ThomasCr** [comment]
![grafik](https://user-images.githubusercontent.com/226670/118989078-083c7900-b982-11eb-8a21-28e788dc2927.png)

**Comment by ThomasCr** [comment]
![grafik](https://user-images.githubusercontent.com/226670/118989708-8ac53880-b982-11eb-8ed8-a50b3d6caece.png)

**Comment by ThomasCr** [comment]
ohhhh.... and what is also funny.... 

When I start FF with extension disabled -> INet works
When I then enable the extension -> INet works
When I restart FF with the enabled extension -> BUG!

**Comment by erosman** [comment]
The process is completely redesigned in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should eliminate the issue.
