### ISSUE TITLE
Is there a way to automatically configure the extension?

### ISSUE THREAD

**Issue by miguelaferreira** [foxyproxy/firefox-extension#152]
I'm using the proxy features of the extension to configure proxies for Firefox users. I need to automatically provision Firefox for my uses, including the extension and the proxy configuration.

Is there a way to provision the proxy configuration in the extension without user interaction?

**Comment by ericjung** [comment]
Hi, I think the best you can do right now is ask users to click the "Import Settings" link in FoxyProxy, then select a file with settings you provide to them. I know that's not completely automatic.
