### ISSUE TITLE
Wrong selected proxy shown in the toolbar icon

### ISSUE THREAD

**Issue by liar666** [foxyproxy/firefox-extension#153]
Hi,

As can be seen in the attached screenshot, the Green "libgen" entry is displayed in the toolboar's icon, whereas it's actually the Orange "Proxys by pattern" that is selected within the possible choice dialog.

![foxybug](https://user-images.githubusercontent.com/3216927/126283045-5cb546fa-5849-4fa6-a2fe-3bd7bfbc6f57.png)

**Comment by ericjung** [comment]
If this is a reproducible bug, please export settings and send them to me. you can remove sensitive info in the exported JSON file. And if you don't want to post it here, then send it to me directly.

If this is a one-time bug, please ignore: it is likely the Firefox toolbar icon API not updating the image.

**Comment by hilari0n** [comment]
> As can be seen in the attached screenshot, the Green "libgen" entry is displayed in the toolboar's icon, whereas it's actually the Orange "Proxys by pattern" that is selected within the possible choice dialog.

@liar666 : As far, as I understand, when the option to use proxies "by patterns and order" is selected, the icon will show you the proxy, which was picked for the page you are on, based on the rules (or the last one used, when different components of the page satisfy different rules). So the behavior may not be intuitive, but is not necessarily incorrect.

**Comment by ericjung** [comment]
@hilari0n thanks. You are right, of course. Given your insight and lack of response from @liar666 , I'm closing this. @liar666  please reply if you have new information.
