### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/firefox-extension#158]
Since FoxyProxy is available for the Android version of Firefox.
The UI should be upgraded to support mobile screens.
At moment the UI is tiny and very hard to interact with without zooming.

See also: #119

I'm currently using:
Edition: FoxyProxy Standard
Version: 7.5.1

Firefox-Nightly: (Android10)
94.0a1 (Build #2015834283)
AC: 94.0.20210914190126, 0b349f48c9
GV: 94.0a1-20210913213224
AS: 84.0.0

**Comment by ericjung** [comment]
Thanks. I'm working on it.

**Comment by erosman** [comment]
[FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) is aiming to have improved Android support.

**Comment by TriMoon** [comment]
@erosman , thanks for so much work...(It took some time hehe)
But uhmm how i test it on mobile, cause that was the Title :wink: 
The instructions in the README are for desktop, they don't work on mobile..
The version available for Mobile via addons is not v8..

**Comment by erosman** [comment]
FoxyProxy Basic should be released very soon.
It has the same code as FoxyProxy.
You can try that one.

**Comment by ericjung** [comment]
@TriMoon foxyproxy basic 8.0 released and is available on mobile. Can you try it?

**Comment by TriMoon** [comment]
@ericjung, Just tried and here is results...
1. Disabled pre-v8 version on mobile.
1. Installed V8 on Mobile via add-ons page.
1. Allowed Private pages setting.
1. Transferred v8 JSON from desktop to Mobile via Bluetooth.
1. Imported the JSON in V8 on mobile.
1. Enabled proxy to use the new settings.
1. But it's not working, because:
   1. The tor check page returns it's not using tor. (Yes im running tor on my mobile also...)
   1. The Log page shows no entries while reloading another tab.

---
> [!NOTE]
I now reverted to pre-v8 version again on mobile...

**Comment by ericjung** [comment]
@TriMoon  thanks! When you disabled pre-8.0, did you do that in FoxyProxy itself or in Firefox? My understanding, at least on desktop, is that if you don’t disable within Firefox itself, then two addons with proxy permissions will conflict. So disable within FoxyProxy is not sufficient…

**Comment by TriMoon** [comment]
I disabled the addon in firefox addons page :wink:
