### ISSUE TITLE
Search suggestions missing after turned on the addon.

### ISSUE THREAD

**Issue by dspjm** [foxyproxy/firefox-extension#160]
Even if I turn off all the blacklists, or select Use Firefox Settings. The search suggestions are not using the proxy. If I turned off the add-on, then search suggestions are back.

**Comment by ericjung** [comment]
hello, please turn on FoxyProxy logging and paste the results here (screenshot preferred).

**Comment by dspjm** [comment]
![image](https://user-images.githubusercontent.com/3742673/136880727-078d60dd-163f-4515-ae92-7b0b25cf323d.png)

**Comment by dspjm** [comment]
I types good job in the search bar and this is what it shows.

**Comment by dspjm** [comment]
> 
> 
> According to the screenshot, all of those URLs were loaded through the proxyserver on localhost because you have FoxyProxy set to ignore patterns (_For All URLs_). Is that what you want?

Yes, I would like all URL to use the proxy. But why the search suggestions are not showing? This problem seemed to happen lately, from 93.0, maybe. I believe I haven't changed related settings.

**Comment by ericjung** [comment]
According to the log/screenshot, search suggestions are also loading through the proxy server. Do you see something different?
