### ISSUE TITLE
Websockets traffic not sent to proxy

### ISSUE THREAD

**Issue by jemjensen** [foxyproxy/firefox-extension#161]
Behavior: When FoxyProxy is configured to forward traffic through a proxy, HTTP/S traffic is forwarded correctly but Websockets traffic is sent directly. Turning off FoxyProxy and configuring Firefox to use the same HTTP proxy using the Firefox settings results in the Websockets traffic going through the proxy as expected.

Expectation: FoxyProxy would behave in the same way as the Firefox settings does, forwarding both HTTP and Websockets traffic through the proxy when one is configured.

OS: macOS Big Sur 11.6
Browser: 93.0 (64-bit)
FoxyProxy: 7.5.1

**Comment by erosman** [comment]
There are browser bugs relating to the issue of WebRTC bypassing browser proxy settings. We are waiting for them to be fixed.

**Comment by erosman** [comment]
- Is that when using proxy by patterns or all through a single proxy?
- If patterns, what is the pattern and was it set to ALL?

**Comment by ExperiBass** [comment]
Not OP but having the same problem.

> * Is that when using proxy by patterns or all through a single proxy?
It appears to be both, disabling all my patterns had no effect.

> * If patterns, what is the pattern and was it set to ALL?
pattern was `*.home` (wildcard) and it was set to ALL.

**Comment by erosman** [comment]
All further development will be in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

I have tested and the WS/WSS are processed for being proxied (if set to a proxy) in v8.0.
