### ISSUE TITLE
Support for chrome.storage.managed

### ISSUE THREAD

**Issue by p3lim** [foxyproxy/firefox-extension#162]
Adding support for [chrome.storage.managed](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) allows support for configuring FoxyProxy through policies (e.g. corporate environments): https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

**Comment by ericjung** [comment]
This is great! I did not know about. Glad to add support for it to FoxyProxy.

**Comment by erosman** [comment]
> Items in managed storage are set by the domain administrator or other native applications installed on the user's computer and are read-only for the extension. Trying to modify this storage area results in an error.

`storage.managed` is best suited to specific set-ups where users are prevented from making changes to the settings. It would appear to defeat its purpose in normal FoxyProxy extension.

In other words, either `storage.managed` has to be used or normal `storage.local`.

Therefore, it would require a specifically built FoxyProxy that uses `storage.managed` and not have the user options code & UI.

**Comment by ericjung** [comment]
> storage.managed is best suited to specific set-ups where users are prevented to make changes to the settings. It would appear to defeat its purpose in normal FoxyProxy extension.

It is not for home users, but for users in very large corporations. Such corporations give their employees locked-down devices without admin access. The configuration of corporate proxy is often remotely managed (the proxy address maybe change, for example, and asking 10,000 employees to follow instructions on how to change the  corporate proxy IP address is not a good idea, and they may not have access to do it on a windows machine if the corporate proxy is managed through network settings).

can we add a Boolean checkbox option, “use  managed storages?” Default false/off.

**Comment by erosman** [comment]
> can we add a Boolean checkbox option, “use managed storages?” Default false/off.

Yes... but then user can change it and bypass corporation settings.

**Comment by ericjung** [comment]
@p3lim  there needs to be a way for people who not in a managed corporate environment to change FoxyProxy settings. How do you propose FoxyProxy serve both sets of people?

**Comment by p3lim** [comment]
If a policy configures foxyproxy, then those options are immutable. For normal users this would never occur.

**Comment by p3lim** [comment]
Fwiw, I raised the same issue with the [Bitwarden clients](https://github.com/bitwarden/clients/issues/2160) and they've implemented it.

**Comment by erosman** [comment]
Creating an enterprise version of FoxyProxy is possible and advisable.

It would be a cut down version, as in enterprise version, there is no need to have UI for options and settings.

**Comment by ericjung** [comment]
> It would be a cut down version, as in enterprise version, there is no need to have UI for options and settings.

We should still have a minimal read-only UI to display the settings to the user - so they know which proxies and patterns are defined an can view the Logging tab.

**Comment by p3lim** [comment]
> We should still have a minimal read-only UI to display the settings to the user - so they know which proxies and patterns are defined an can view the Logging tab.

I agree, and having separate versions increase the maintenance burden, and required administrators that maintain these policies to run multiple browsers (or separate profiles of a single one) when developing rules. It is entirely possible to do this without separating it into a gutted version, although the initial workload to display the fact that it is enterprise managed would be greater.

**Comment by ericjung** [comment]
> > We should still have a minimal read-only UI to display the settings to the user - so they know which proxies and patterns are defined an can view the Logging tab.
> 
> I agree, and having separate versions increase the maintenance burden, and requires administrators that maintain these policies to run multiple browsers (or separate profiles of a single one) when developing rules. It is entirely possible to do this without separating it into a gutted version, although the initial workload to display the fact that it is enterprise managed would be greater.

Yes, it is possible. But I reviewed the BitWarden stuff you linked to and reviewed their code. It's not exactly straightforward to me how to they handle local vs. sync vs. managed settings (there are 3 possible storage solutions - local disk, synchronized disk, and managed - the first two are for non-enterprise users. currently we have a switch in FoxyProxy for the user to select between local and synchronized. we would need to disable that or hide it somehow if we detect managed storage exists at startup, i guess. i just did not see how bitwarden implemented this).

**Comment by erosman** [comment]
MDN [Native manifests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) states that the manged storage must be placed in a specific location on user's computer. There doesn't appear to be a system to get it from a remote server.

**Comment by ericjung** [comment]
> MDN [Native manifests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) states that the manged storage must be placed in a specific location on user's computer. There doesn't appear to be a system to get it from a remote server.

I would expect the managed storage to be pushed to the user's computer from the IT department. We're talking about devices in a corporate environment that are heavily locked down and remotely managed, where the users generally do not have admin access on their own devices.

**Comment by p3lim** [comment]
The managed storage doesn't really exist in that sense. The browser is configured by the company policy, which would include the extension policies. The extension uses these policies as a configuration (through the storage.managed api).

**Comment by ericjung** [comment]
@p3lim can you share the product that you use for this management? I wonder if they have some kind of trial that I can test to see how it works with managed storage. Does it simply push a file to the remote machines that represents managed storage?

**Comment by p3lim** [comment]
> Does it simply push a file to the remote machines that represents managed storage?

Yup, you could use any configuration management system for this, you just place the policy json file on every computer.

https://support.mozilla.org/en-US/products/firefox-enterprise/policies-customization-enterprise/policies-overview-enterprise

**Comment by erosman** [comment]
Please note the structure in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension):

- All editing is done in Options page (no selecting/switching proxies)
- All selecting/switching is done in Toolbar popup

For clarification purposes ...

- Will users be able to access FoxyProxy Options and edit them?
- Will users be able to access FoxyProxy toolbar popup and select proxies?
- Should pre-set config be checked/loaded at browser start-up, or also periodically during the operation?
- How often the pre-set config is expected to change?

**Comment by erosman** [comment]
Added managed storage feature for v8.2 (experimental)
