### ISSUE TITLE
Not intercepting raw IP Addr?

### ISSUE THREAD

**Issue by SamKomesarook** [foxyproxy/firefox-extension#165]
Hi, thank you for this extension!

I am using it to route traffic to Burp, and it works perfectly for normal URLs like `https://google.com`, however if I type a remote IP addr accepting traffic on ports 80 or 443, such as `10.11.11.5` or `http://10.11.11.5`, that traffic is not intercepted through Burp. The only rule in my proxy is the default `*` wildcard.

I thought the issue might have been Firefox doing something strange with the IP addr, however the Firefox dev tool network logs show a clean request (`http://10.11.11.5`) being made, which should be captured under the `*` wildcard rule in my proxy. Just curious if this is a problem you might have seen before, and if I require different settings in my proxy.

**Comment by ericjung** [comment]
Hello Sam,

Do you have blacklist patterns? Can you:

1. Paste a screenshot of your patterns or
2. Turn on logging on FoxyProxy, visit the problematic URL/ip address, the paste a screenshot of the log or
3. Export your FoxyProxy settings and paste here (you can remove sensitive info if there is any)

thank you

**Comment by SamKomesarook** [comment]
Ah I apologise, I didn't check the logging. Looks like my pattern is matching the IP, so it must be something with Burp. Thank you for the quick response!
