### ISSUE TITLE
'FoxyProxy ignores everything on this page unless . . ': cited setting unfindable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [foxyproxy/firefox-extension#168]
![image](https://user-images.githubusercontent.com/47056543/150624653-6c8c2452-4130-4b2e-90d0-871f6092bfe1.png)

Where is that option? I could not find it anywhere. Presuming the option exists: the user should be able to find it easily.

FoxyProxy Standard, version 7.5.1, on Firefox 96.0.1, on Linux Mint.

**Comment by shaqman** [comment]
> ![image](https://user-images.githubusercontent.com/47056543/150624653-6c8c2452-4130-4b2e-90d0-871f6092bfe1.png)
> 
> Where is that option? I could not find it anywhere. Presuming the option exists: the user should be able to find it easily.
> 
> FoxyProxy Standard, version 7.5.1, on Firefox 96.0.1, on Linux Mint.

When ypu open the extension, it shows that option quite clearly. See following image

![image](https://user-images.githubusercontent.com/1113851/151634414-4eb4b751-72d0-45fe-af6f-6c83ca4147d4.png)

**Comment by LinuxOnTheDesktop** [comment]
Thanks. But: (1) yellow on white is not very visible; (2) the user needs to know that she should click on the extension's button, rather (yes? I no longer have the addOn installed) that look in Firefox's AddOn options.

**Comment by shaqman** [comment]
> Thanks. But: (1) yellow on white is not very visible; (2) the user needs to know that she should click on the extension's button, rather (yes? I no longer have the addOn installed) that look in Firefox's AddOn options.

I as a user actually prefer this method. This way we could switch how foxyproxy works on the fly.
Anyway, the way to think why the placement is optimal is because it is not an option, rather than a mode.

When you wan't to use a specific proxy, you can. When you want to disable all proxies, you can. And when you need for foxyproxy to decide when to use based on patterns, you also can. That way, the current placement is optimal.

That being said, what do you propose to make it easier to understand?

**Comment by LinuxOnTheDesktop** [comment]
1 can be remedied by changing colours.

2 can be remedied thusly. Make the options accessible not only via the button but also via the options button shown here:

![image](https://user-images.githubusercontent.com/47056543/151637684-7224d4b5-2d5c-4388-a8b2-a03295abfd11.png)

Clicking that button yields the following.

![image](https://user-images.githubusercontent.com/47056543/151637842-ac48015a-4c7d-4128-a764-3d7e106ab052.png)

If the 'on the fly' options that we have been discussing are available via the depicted page (are they?) then it should be made easier to find them from that very page.

**Comment by shaqman** [comment]
1. Yellow on white is still consistent with the menu inside, and it's the same color is the menu inside
2. I still think you are missing the point. It's not an option, rather than a mode.

**Comment by LinuxOnTheDesktop** [comment]
Your point about _1_ does not stop legibility being a problem.

Re _2_: hmm. Perhaps _you_ miss the, or at least a, point. That point is: important toggle-ables need to be easily discoverable. If you will not ensure that discoverability via anything entitled 'options' (on the basis that the toggle in question is not strictly an option) then you need to find some other way of making the toggle discoverable. How? Well, at the least, you could amend the message with which I started this bug report. Amend it such that it says how to access the toggle.

**Comment by ericjung** [comment]
@LinuxOnTheDesktop  on don't understand what you're asking about #2. The options are available when clicking the options/preferences (as it is called on macOS firefox) link from the about:addons page.

**Comment by LinuxOnTheDesktop** [comment]
@ericjung 

My point is this. It is hard to discover where the 'Use enabled proxies by patterns . .' is.

**Comment by ericjung** [comment]
@LinuxOnTheDesktop ok, got it. Maybe it's because I'm too close to the software to know otherwise, since I designed this UI, but I can't think of another way to make it more discoverable.

**Comment by shaqman** [comment]
> Your point about _1_ does not stop legibility being a problem.
True. What I meant by saying that is, I failed to notice why the mode becomes a problem while the options does not.


> Re _2_: hmm. Perhaps _you_ miss the, or at least a, point. That point is: important toggle-ables need to be easily discoverable. If you will not ensure that discoverability via anything entitled 'options' (on the basis that the toggle in question is not strictly an option) then you need to find some other way of making the toggle discoverable. How? Well, at the least, you could amend the message with which I started this bug report. Amend it such that it says how to access the toggle.

No. I do get your point. Like I said, it's quite discoverable for me, and for most of users it seems.
That is why I was asking, what do you propose to make it more discoverable, considering that one is an option, while the other is a mode. I am not saying it shouldn't be easily discoverable, I'm asking on your opinion on how to make it so.

While I see you are suggesting to amend the message, I fail to see how that helps.

**Comment by LinuxOnTheDesktop** [comment]
@Both

Thanks for your responses. Here is why amending the message would help. One reason that the user can have to want to find the toggle in question is that she (the user) has been told about that toggle by the message. If having read the message the user seeks the toggle she might not find it. Were the message to give the toggle's location, then she would find it.

**Comment by funnyzzz1387** [comment]
#159

**Comment by erosman** [comment]
re: Themes

Complete Light/Dark Theme is implemented in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension)

**Comment by erosman** [comment]
UI is redesigned in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should eliminate the issue.
