### ISSUE TITLE
An option for proxy profiles to run only on specific Wi-Fi network or mobile network

### ISSUE THREAD

**Issue by Monsterovich** [foxyproxy/firefox-extension#173]
The proxy which I use doesn't work when I use LTE or foreign Wi-Fi network. That's why I'm forced to enable/disable the profile every time I switch networks, ex. `Wi-Fi ↔ LTE` or `home Wi-Fi network ↔ another Wi-Fi network`, or when I use Android VPN.

Is it possible to delegate proxy profiles to separate network set-ups?

**Comment by ericjung** [comment]
FoxyProxy Plus had this feature some years ago. Unfortunately, the ability to get the intranet IP address from a browser extension was removed from Firefox. As far as I know, there is no way to get it anymore. So, this feature is not technically possible. I am open to being corrected, but closing this ticket unless I get other information.
