### ISSUE TITLE
Advanced Import: Title does not recognise anthing after "#"

### ISSUE THREAD

**Issue by absywabsy** [foxyproxy/firefox-extension#184]
Hi,

I like to label my proxies with numbers and I use # to denote "number" and it's a big symbol that breaks things up. When I want to mass import and use # in the title, the importer successfully imports but ignores anything written after the #

Is there a way around this?

**Comment by ericjung** [comment]
Probably not. The importer is stripping out certain characters in order to prevent XSS vulnerabilities. Sorry.
