### ISSUE TITLE
New language suggestion

### ISSUE THREAD

**Issue by R0htg0r** [foxyproxy/firefox-extension#185]
Hello,

I have a translation ready in Portuguese to be added to FoxyProxy.

File: https://github.com/R0htg0r/FoxyProxy_PT-BR/blob/main/messages.json

**Comment by ericjung** [comment]
Thank you.

**Comment by erosman** [comment]
Added to [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).
