### ISSUE TITLE
Please use more inclusive language in the pattern editor

### ISSUE THREAD

**Issue by proski** [foxyproxy/firefox-extension#186]
"White Patterns" and "Black Patterns" sounds outdated and culture dependent. There are also terms "Whitelist" and "Blacklist" in the web documentation.

Please try describing the functionality by using specific, inclusive and culture-independent language. For instance, patterns could be either sufficient (the rule applies if the pattern matches) and forbidden (the rule doesn't apply if the pattern matched), It shouldn't be necessary to group them to separate lists, they can be in single "rule list",

I would appreciate if you steer clear of the term "blocklist", it's ambiguous (it could be a list of blocks), it sounds like a thinly veiled "blacklist" and it doesn't translate well (it's translated to what means "black list" to many languages).

**Comment by erosman** [comment]
include/exclude could be a possibility.

**Comment by ericjung** [comment]
Thank you for your feedback. We are working on the next major release of FoxyProxy so it remains compatible with major changes to the Firefox and Chrome extension library (called "Manifest v3"). We will consider all feedback from the users.
