### ISSUE TITLE
Selecting proxy based on network addresses

### ISSUE THREAD

**Issue by proski** [foxyproxy/firefox-extension#187]
For many users, the choice of the proxy is not determined by the URL they are trying to reach, it's determined by the network they are on. For instance, a 10.0.0.0/8 address would indicate an office whereas 192.168.0.0/16 is probably a home network. Yet 192.168.49.0/24 is probably when they are using Android NetShare and need a proxy.
Please consider adding rules where the presence local address (IPv4 or IPv6) in a specified range determines whether the proxy is used.

**Comment by ericjung** [comment]
FoxyProxy Plus had this feature some years ago. Unfortunately, the ability to get the intranet IP address from a browser extension was removed from Firefox. As far as I know, there is no way to get it anymore. So, this feature is not technically possible. I am open to being corrected.

**Comment by ericjung** [comment]
see also https://github.com/foxyproxy/firefox-extension/issues/173
