### ISSUE TITLE
Pattern tester breaks on Cyrillic URLs

### ISSUE THREAD

**Issue by InvisibleRain** [foxyproxy/firefox-extension#193]
Steps to reproduce:
1. Go to moz-extension://eb06d607-ee6f-4a07-8d51-55c4fb32ae87/pattern-tester.html
2. Paste `http://культура.рф/` Into "Step 1. Enter URL to test"
3. Paste `*.рф` into "Step 2. Enter pattern details"
4. Press "Test"

Given result: Pattern does not match URL
Expected result: Pattern matches

This issue is also reproducible on all non-Latin URLs (e.g. Chinese, Hindi, Japanese and so on)

**Comment by erosman** [comment]
Development is concentrated on the next major release of FoxyProxy.

However, there is no issue with the above in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

![tester](https://user-images.githubusercontent.com/6458876/194109352-e67bbb5f-1379-4782-9cb4-f7aaaca4ef04.png)

**Comment by InvisibleRain** [comment]
Sounds awesome! Can't wait to see it being released

**Comment by InvisibleRain** [comment]
In the meanwhile, a temporary workaround is to enter the domain names in Punycode. There's a good online tool for converting domains to punycode: https://www.charset.org/punycode
