### ISSUE TITLE
Support large pattern

### ISSUE THREAD

**Issue by xmha97** [foxyproxy/firefox-extension#203]
Please support the large pattern
[foxyproxy-NekoRay-patterns_2023-06-16.json](https://github.com/foxyproxy/firefox-extension/files/11770039/foxyproxy-NekoRay-patterns_2023-06-16.json.txt)

**Comment by erosman** [comment]
What is 'large" pattern?

- Length of an individual pattern?
There is no limit in v8.0.
- Number of patterns?
There is no limit in v8.0.
- Overall size of the database?
There is no limit in v8.0.
The only limit is what is set by the browser and user's hard-disk.

**Comment by xmha97** [comment]
Sorry, the problem was with my file.
Thank you for making this extension.
