### ISSUE TITLE
Is it possible to import settings from a file? My goal is to have a pre-configured proxy that can be used without having to first import settings by using the import-function in the browser or adding a proxy manually.

### ISSUE THREAD

**Issue by Bomb336** [foxyproxy/firefox-extension#205]
Is it possible to import settings from a file? My goal is to have a pre-configured proxy that can be used without having to first import settings by using the import-function in the browser or adding a proxy manually.
If so where does the settings-file need to be put and what is the required structure of the file?

_Originally posted by @Pt-PhilW in https://github.com/foxyproxy/firefox-extension/discussions/191_

**Comment by erosman** [comment]
Import-export settings does just that. You can edit it and import the edited one.

Import Proxy List also can be used to import proxies.

All further development will be in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (currently in beta).
