### ISSUE TITLE
Import-export settings does just that. You can edit it and import the edited one.

### ISSUE THREAD

**Issue by Bomb336** [foxyproxy/firefox-extension#206]
Import-export settings does just that. You can edit it and import the edited one.

Import Proxy List also can be used to import proxies.

All further development will be in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (currently in beta).

_Originally posted by @erosman in https://github.com/foxyproxy/firefox-extension/issues/205#issuecomment-1640208195_

**Comment by erosman** [comment]
What is the question?
