### ISSUE TITLE
[Feature request] Optional static toolbar icon

### ISSUE THREAD

**Issue by sk2449** [foxyproxy/firefox-extension#207]
On websites with ongoing dynamically loaded content and only some of it sent through a proxy based on patterns, the toolbar icon can be observed switching between "vpn" (green) and "No" (red) every few seconds, which is distracting and offers no useful information (= cannot be correlated with traffic anyway unless the logging feature is used additionally) - especially when the indication is related to traffic from a different tab.

Suggestion: Introduce an option to lock the icon's appearance in pattern based mode to avoid unnecessary flashing, e.g. by using a static orange icon, that the icon only reflects the addon's current matching mode instead of the most recent pattern decision.

**Comment by erosman** [comment]
This is no longer an issue in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

**Comment by sk2449** [comment]
Awesome. Will give the beta a try with the installation instructions found at https://github.com/foxyproxy/browser-extension/issues/1. Thank you!
