### ISSUE TITLE
HTTPS proxy only works when added as HTTP (no S) Proxy Type

### ISSUE THREAD

**Issue by bam80** [foxyproxy/firefox-extension#209]
I added HTTPS proxy as HTTPS/SSL Proxy Type but have this error when I try to open any HTTPS site:

> Secure Connection Failed
>
> An error occurred during a connection to wise.com. SSL received a record that exceeded the maximum permissible length.
> 
> Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
>    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>    Please contact the website owners to inform them of this problem.

The proxy requires authentication but I filled Username/Password properly.
The same proxy works being added as HTTPS in built-in Network Settings.

When I change the Proxy Type to just HTTP, everything start work.

**Comment by erosman** [comment]
The error relates to the SSL from the proxy server. It has nothing to do with FoxyProxy.
Firefox did not accept the SSL data sent by the proxy server.

> When I change the Proxy Type to just HTTP, everything start work.

With HTTP proxy, there is no SSL data exchange, therefore there wont be an error (but the data in transit is not encrypted).
