### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by kuklofon** [foxyproxy/firefox-extension#210]
"Откоючить" is wrong
"Отключить" is right
<img width="497" alt="изображение" src="https://github.com/foxyproxy/firefox-extension/assets/20505953/82363bf5-80f4-46a8-99d0-4664ea839b2c">

UPDATE
But it's right in code..
<img width="676" alt="Снимок экрана 2023-08-16 в 07 21 46" src="https://github.com/foxyproxy/firefox-extension/assets/20505953/79c490d3-875b-4d06-a73d-ccce062cf1b4">

**Comment by ssh3** [comment]
@kuklofon hm, I was going to create an issue of the same reason. :)

**Comment by Kubrix** [comment]
Please fix this issue

**Comment by ericjung** [comment]
Thank you. Please check if it is correct here:
https://github.com/foxyproxy/browser-extension/tree/main/src/_locales
That is the next release.

**Comment by kuklofon** [comment]
> Thank you. Please check if it is correct here: https://github.com/foxyproxy/browser-extension/tree/main/src/_locales That is the next release.
Now that's right, there are no more errors

**Comment by kuklofon** [comment]
> Thank you. Please check if it is correct here: https://github.com/foxyproxy/browser-extension/tree/main/src/_locales That is the next release.

Now that's right, there are no more errors
