### ISSUE TITLE
Do not show disabled proxy

### ISSUE THREAD

**Issue by Kubrix** [foxyproxy/firefox-extension#211]
Edition: FoxyProxy Standard
Version: 7.5.1
UK aand NDL are turned off
Why do I see them from the menu
![image](https://github.com/foxyproxy/firefox-extension/assets/33233100/3f7931db-8df1-4f8e-8663-a155840aede9)

**Comment by erosman** [comment]
The issue has been fixed in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

**Comment by Kubrix** [comment]
Not fixed in v8.0

![image](https://github.com/foxyproxy/firefox-extension/assets/33233100/efdbfb3f-65e8-48c3-919e-a99085d4fd0d)

**Comment by Kubrix** [comment]
Moreover - i think extension was unstalled after closing FF
As extesntion was added as temporary
