### ISSUE TITLE
Broken functionality with SOCKS5 proxy

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/firefox-extension#213]
When configured to use a SOCKS5 proxy for an address the web page doesn't work.

Example:
- Proxy _(tor)_: SOCKS5 `127.0.0.1` port `9050`
- Site: https://www.atv.com.tr/canli-yayin and similar live TV sites.
- Rule: `^[a-z]+://[\w.-]*(radiantmediatechs|daioncdn)\.\w+/`

Result in Firefox "Web Developers Tools":
- `cdn.radiantmediatechs.com` gets blocked with `NS_ERROR_DOM_CORP_FAILED`
_(and similar namespace errors for other sites that access URL's from within javascript)_

![image](https://github.com/foxyproxy/firefox-extension/assets/1723378/1125ed1d-ae42-452c-a2b1-4e097951bdb5)

---
> [!NOTE]
> This same bug happens both in the old FoxyProxy-Standard from addons site, and this new v8 version...
>
> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0 ID:20230915003051
> _(Latest snap version of Firefox on Kubuntu 23.04)_

**Comment by erosman** [comment]
Are you loading the page with a different proxy (or no proxy) and loading the `cdn.radiantmediatechs.com` with a different one?

https://searchfox.org/mozilla-central/source/xpcom/base/ErrorList.py#732-735
```
# Used to indicate that a resource with the Cross-Origin-Resource-Policy
# response header set failed the origin check.
# https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header
errors["NS_ERROR_DOM_CORP_FAILED"] = FAILURE(1036)
```

**Comment by TriMoon** [comment]
Seems i posted in wrong repo :woman_facepalming:
Anyhow re-posted at: https://github.com/foxyproxy/browser-extension/issues/31

**Comment by TriMoon** [comment]
Seems i posted in wrong repo :woman_facepalming:
Anyhow re-posted at: https://github.com/foxyproxy/browser-extension/issues/31
