### ISSUE TITLE
Network detection feature.

### ISSUE THREAD

**Issue by R0Z-Z** [foxyproxy/firefox-extension#216]
Hello,

I make use of foxyproxy for people that work remotely, and seldom coming to office. Unfortunately, I could not make them care for changing foxyproxy to patterns mode when they leave our office. Is it possible to add a network detection method that conditionally changes proxies or turn it off? I mean, for example: if in 192.168.32.0/24 turn off. If not in 192.168.32.0/24 use patterns mode. 

If this is acceptable as a feature request, I'd really appreciate to see such a thing in foxyproxy. Thank you for this great useful tool. You make a sysadmin's life easier. 

All the best... :)

PS: I'd like to donate what I can, however, Paypal does not work in my country. Perhaps you might think adding USDT or BTC wallet info for donations.

**Comment by erosman** [comment]
Refer to [Network detection feature.](https://github.com/foxyproxy/browser-extension/issues/37)
