### ISSUE TITLE
Please add keyboard shorcuts

### ISSUE THREAD

**Issue by sajadspeed** [foxyproxy/firefox-extension#217]
Please add the possibility of using shortcuts to change the proxy. I switch between proxies a lot and it's a pain to use the mouse every time. Thank you.

**Comment by ericjung** [comment]
This is already done in FoxyProxy 8.x. You can get it here:

https://github.com/foxyproxy/browser-extension#installation-guide-for-testing

**Comment by sajadspeed** [comment]
Thank you very much, but when will this version be officially released if I don't want to use the testing version?

**Comment by ericjung** [comment]
Firefox: likely 2 weeks. Chrome: likely 4 weeks.
