### ISSUE TITLE
Unable to intercept localhost

### ISSUE THREAD

**Issue by imapotato123** [foxyproxy/firefox-extension#218]
Is there an option to allow for interception of webservers on localhost? Option was enabled in firefox's about:config to enable localhost hijacking but foxyproxy still does not pass data through the proxy. Understood this is a security control but is there a way to override the setting?

**Comment by erosman** [comment]
It is already fixed since v8.4
Check [About](https://foxyproxy.github.io/browser-extension/src/content/about.html) for more information.
