### ISSUE TITLE
Can't open google service PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by depocoder** [foxyproxy/firefox-extension#224]
Hi, I tried the bunch of proxies and proxies types. Each time, I have issue with entering https://play.google.com/.

<img width="686" alt="SCREEN PR_CONNECT_RESET_ERROR" src="https://github.com/user-attachments/assets/7cce73a9-697f-4f61-a2ed-b2b19d6c08ca">

I don't have problems with other sites. 

Debug info:
OC: Windows 10 licensed
Logs:
![изображение](https://github.com/user-attachments/assets/8a137e8b-f399-48ce-a460-a1db5946529f)

**Comment by erosman** [comment]
Which version of FoxyProxy are you using?
This repo is for v7.5 and older.

**Comment by depocoder** [comment]
> Which version of FoxyProxy are you using? This repo is for v7.5 and older.

Hi, I tried from Firefox extension store and from repo latest release too.

**Comment by erosman** [comment]
If you are using version 8+, it is better to use the [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

**Comment by depocoder** [comment]
> If you are using version 8+, it is better to use the [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

Haven't helped
 
![img](https://github.com/user-attachments/assets/83a48d31-bb05-413c-b57b-a72fc4fa0930)


![img](https://github.com/user-attachments/assets/335e824e-fac2-4547-bd43-775296573c6e)

![img](https://github.com/user-attachments/assets/9f5818e8-3f2a-4aa4-8bdf-46a267dd144a)

**Comment by depocoder** [comment]
Tried on Ubuntu same issue, tried other proxies same issue. What else shall I do? Should I reopen in the new repo?

**Comment by erosman** [comment]
There is not enough information to comment on.

How are you using the proxy? Are you setting the proxy for everything or using Proxy by Patterns?
If you are using Proxy by Patterns, what are the patterns?
What are the settings for the proxy?

**Comment by depocoder** [comment]
> There is not enough information to comment on.
> 
> How are you using the proxy? Are you setting the proxy for everything or using Proxy by Patterns?
> If you are using Proxy by Patterns, what are the patterns?
> What are the settings for the proxy?
> 

Hi, I'm using it for everything. I tried patterns too, same issue.

**Comment by depocoder** [comment]
> There is not enough information to comment on.
> 
> How are you using the proxy? Are you setting the proxy for everything or using Proxy by Patterns? If you are using Proxy by Patterns, what are the patterns? What are the settings for the proxy?

![image](https://github.com/user-attachments/assets/6dfebd3d-c00f-4d0f-8a59-973e822c31f6)

You can try this proxy, I bought it for one month
186.65.117.204:9666 
login: `utLAoG`
pass:  `KKLhj3`

**Comment by erosman** [comment]
I deleted your post to preserve your login privacy.

I will get back to you after some testing.

**Comment by ericjung** [comment]
@erosman shared your proxy details with me, @depocoder. I cannot reproduce the problem. I set FoxyProxy 8.9 to use all URLs for the proxy. The proxy was configured as SOCKS5 with the IP address, port, username, and password that @depocoder provided.

I confirmed my IP address was the IP address of the SOCKS5 proxy server by visiting https://getfoxyproxy.org/geoip/
Then I loaded https://play.google.com which redirected to https://play.google.com/store/games

![telegram-cloud-photo-size-1-5050966125638168125-y](https://github.com/user-attachments/assets/763c7c9b-9d39-4f3e-bf41-5d5c595e7ca4)

I tested on Firefox on 127.0.2,  128.0.3, and 129.0.1  on MacOS.

**Comment by depocoder** [comment]
> @erosman shared your proxy details with me, @depocoder. I cannot reproduce the problem. I set FoxyProxy 8.9 to use all URLs for the proxy. The proxy was configured as SOCKS5 with the IP address, port, username, and password that @depocoder provided.
> 
> I confirmed my IP address was the IP address of the SOCKS5 proxy server by visiting https://getfoxyproxy.org/geoip/ Then I loaded https://play.google.com which redirected to https://play.google.com/store/games
> 
> ![telegram-cloud-photo-size-1-5050966125638168125-y](https://private-user-images.githubusercontent.com/5875610/359185901-763c7c9b-9d39-4f3e-bf41-5d5c595e7ca4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODk0NzgsIm5iZiI6MTcyNDA4OTE3OCwicGF0aCI6Ii81ODc1NjEwLzM1OTE4NTkwMS03NjNjN2M5Yi05ZDM5LTRmM2UtYmY0MS01ZDVjNTk1ZTdjYTQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTczOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEyODEyNGFkM2E4NTU5ZjAxMmE4YjgwMzVlNTVhYWFjNjA1Zjg4NmI1YjczYzg5NGU3NGE1MmU5OWFlZjg1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sjkZJLPmlluSWW8CPnXebsTESBCERk3lhXi_WJX526k)
> 
> I tested on Firefox on 127.0.2, 128.0.3, and 129.0.1 on MacOS.

Thank you, can it be internet provider problem?

**Comment by erosman** [comment]
> Thank you, can it be internet provider problem?

There can be many possibilities e.g.
- another extension can be making changes to the network connection
- the ISP 
- the computer settings
- etc

**Comment by ericjung** [comment]
Try temporarily disabling all firewalls, both on the PC and the router.

**Comment by depocoder** [comment]
> Try temporarily disabling all firewalls, both on the PC and the router.

It was an ISP problem. In Russia, Roskomnadzor is blocking content with DPI. I configured 3X-UI and V2RayA, then I used this chain proxy in foxy proxy, and now I can enjoy the Internet.
