### ISSUE TITLE
"Open link with proxy", "New tab with proxy" features

### ISSUE THREAD

**Issue by t1m013y** [foxyproxy/firefox-extension#225]
Please add "Open link with proxy" and "New tab with proxy" features. It will let open new tab or link in new tab already with proxy enabled. I'm missing this feature.

**Comment by erosman** [comment]
This repository is for FoxyProxy v7.5 and there wont be any further development on it.

For the current FoxyProxy please use [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

**Comment by t1m013y** [comment]
Ok. Copied this issue to [foxyproxy/browser-extension](https://github.com/foxyproxy/browser-extension)
