### ISSUE TITLE
DNS leakage with Firefox Multi-User Containers even without uBlock Origin

### ISSUE THREAD

**Issue by akarelas** [foxyproxy/firefox-extension#226]
Browser: Firefox 130.0
OS: Void Linux
SOCKS5 proxy: [Dante](https://www.inet.no/dante/)

1. I created a new Firefox profile (the same bug also happens on my default profile, though)
2. I installed the Multi-User Containers browser extension
3. I installed the FoxyProxy (Standard) browser extension
4. I added the IP/port of Dante to FoxyProxy proxies, under the proxies tab of FoxyProxy Options, and have the "Proxy DNS" switch of that proxy activated
5. I set "Container 1" (that's the container named "Personal") to this proxy, under the "Options" tab of FoxyProxy options
6. I opened this page: https://www.dnscheck.tools/ with the Personal container
7. I observed that my laptop's DNS servers were used (i.e. there was DNS leakage). The proxy's DNS server also appeared in the list. However the location reported was the one I expected due to proxy being active.

On the other hand, when...

1. I set SOCKS5 settings (in Firefox's Connection Settings screen) to point to my Dante (Select "Manual Proxy Configuration" -> fill in "SOCKS Host" & "Port", select "SOCKS 5" radio button, check "Proxy DNS when using SOCKS v5" checkbox)
2. I view https://www.dnscheck.tools/ without any container
3. I observe only the DNS of my Dante Proxy appearing (ie there is no DNS leakage).

I tried the same thing with Firefox (2 profiles) and with LibreWolf (Firefox fork, 1 profile).

Does it behave differently on your systems? Is it a bug?

**Comment by erosman** [comment]
Which version of FoxyProxy are you using?
This repo is for version 6-7. 

All further development will be in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).

However, as mentioned in https://github.com/foxyproxy/browser-extension/issues/142#issuecomment-2233819048

> FoxyProxy does not handle the DNS. All DNS queries are handled by the browser and therefore it is a browser issue.
> 
> The DNS leak issues have been reported to Firefox and it is due to be sorted.
> 
> See: [[meta] Proxy DNS leak bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1882276)

**Comment by akarelas** [comment]
Oh, thanks. I use FoxyProxy version 8.9. Thanks.
