### ISSUE TITLE
Secure SNI is disabled if FoxyProxy is enabled

### ISSUE THREAD

**Issue by mssucksalot** [foxyproxy/firefox-extension#227]
Tested via https://www.cloudflare.com/ssl/encrypted-sni/ and using Firefox Stable 133

If FoxyProxy is disabled in browser options then CF test is passed and Secure SNI is enabled.

**Comment by erosman** [comment]
Is this for FoxyProxy v7?

Does the proxy server support Secure SNI?

**Comment by mssucksalot** [comment]
> Is this for FoxyProxy v7?
> 
> Does the proxy server support Secure SNI?

If version can be viewed in About then it is:

```
Changelog

8.9
```

Requests must pass directly. I use a `proxy by patterns`, but even if the proxy is disabled the result remains the same.  
So, only disabling extension itself solves the issue (as I mentioned above).

**Comment by erosman** [comment]
This repository is for v7. Please use the v8 repository.

When I test, secure SNI fails even without FoxyProxy from my location on Nightly 135.0a1.

Please also provide a sample setting for testing.

**Comment by mssucksalot** [comment]
> This repository is for v7. Please use the v8 repository.
> 
> When I test, secure SNI fails even without FoxyProxy from my location on Nightly 135.0a1.
> 
> Please also provide a sample setting for testing.

You need to create option: `network.security.esni.enabled` and set to `true` in _about:config_.
