### ISSUE TITLE
Couldn't connect to google.com while i add *le.com* to black patterns

### ISSUE THREAD

**Issue by kktt007** [foxyproxy/firefox-extension#27]
I add many Chinese website to black patterns, then i find i couldn't open google.com. Finally i found it does matter with the website name: *le.com*. A chinese webiste called 乐视, very famous. I don't know why, maybe it's a bug. 

[The wrong log](http://img.vim-cn.com/69/a6c9f97330189d852141e22fe3226d987cd1c2.png )

[Correct log](http://img.vim-cn.com/e2/fd41a9e58a3fb606b9a3574520d1a71fb012ab.png )

**Comment by valepu** [comment]
"*le.com*" will block any website that contains the string "le.com" in the url, "google.com" ends with "le.com". This pattern will also block sites like "doodle.com" since it ends with "le.com"

Try using "le.com*" as pattern (remove the first *)

**Comment by kktt007** [comment]
> 
> 
> "_le.com_" will block any website that contains the string "le.com" in the url, "google.com" ends with "le.com". This pattern will also block sites like "doodle.com" since it ends with "le.com"
> 
> Try using "le.com*" as pattern (remove the first *)

Thank you. Right. Google.com contains "le.com". I think i shoud use *.foo.com* , right? the two * is must be needed. I test a lot of patterns below:
1. ||foo.com is wrong.   || couldn't be used. (because i use this in switchyomega on google: ||foo.com is the best)
2. foo.com is wrong.  there are no * and the two sides.
3. \*foo.com\* may cause soem issues like : googlefoo.com
so just \*.foo.com\* is correct, am i right?  Thank you in advanced.

**Comment by ericjung** [comment]
> "_le.com_" will block any website that contains the string "le.com" in the url, "google.com" ends with "le.com". This pattern will also block sites like "doodle.com" since it ends with "le.com"

Not entirely true. **le.com** only matches google.com and doodle.com if you created that pattern as a **regular expression**. It does not match if it's a **wildcard** pattern.

@kktt007 seems to be using wildcard patterns because he mentions:

> *foo.com* may cause some issues like : *googlefoo.com* contains *foo.com*
so just *.foo.com* is correct, am i right? Thank you in advanced.

I do not know what you are trying to match. Can you explain?

> another question. I want to add all foo.cn to blackpattern. I use .cn (also *.cn), i found it also block https://img.vim-cn.com/ . I just want to block ".cn". Confused.

Use *.cn  -- it matches all URLs at .cn and all subdomains like foo.cn and bar.foo.cn

**Comment by kktt007** [comment]
> 
> 
> > "_le.com_" will block any website that contains the string "le.com" in the url, "google.com" ends with "le.com". This pattern will also block sites like "doodle.com" since it ends with "le.com"
> 
> Not entirely true. **le.com** only matches google.com and doodle.com if you creat that pattern as a **regular expression**. It does not match if it's a **wildcard** pattern.
> 
> @kktt007 I do not know what you are trying to match. Can you explain?
> 
> > another question. I want to add all foo.cn to blackpattern. I use .cn (also *.cn), i found it also block https://img.vim-cn.com/ . I just want to block ".cn". Confused.
> 
> Use wildcard `*.cn` -- it matches all URLs at `.cn` and all subdomains like `foo.cn` and `bar.foo.cn`. You can also try `**.cn` -- that matches URLs only at subdomains of `.cn` but not `.cn` itself (since there is nothing at just `.cn` that should be OK to use)

Thank you tell me `**.cn`. So cool.

I want to test this: foo.com
1. `foo.com`
2. `.foo.com`
3. `*foo.com*`
4. `*.foo.com*`
I think a dot "." is needed, right? Above, 2 and 4 is better than 1 and 3, right? 
Are there any difference between 2 and 4.
Thanks again.

**Comment by valepu** [comment]
> > "_le.com_" will block any website that contains the string "le.com" in the url, "google.com" ends with "le.com". This pattern will also block sites like "doodle.com" since it ends with "le.com"
> 
> Not entirely true. **le.com** only matches google.com and doodle.com if you creat that pattern as a **regular expression**. It does not match if it's a **wildcard** pattern.
> 
> @kktt007 I do not know what you are trying to match. Can you explain?
> 
> > another question. I want to add all foo.cn to blackpattern. I use .cn (also *.cn), i found it also block https://img.vim-cn.com/ . I just want to block ".cn". Confused.
> 
> Use wildcard `*.cn` -- it matches all URLs at `.cn` and all subdomains like `foo.cn` and `bar.foo.cn`. You can also try `**.cn` -- that matches URLs only at subdomains of `.cn` but not `.cn` itself (since there is nothing at just `.cn` that should be OK to use)

I'm sorry, i had put * in my message but did not notice they were turned into italic text, i meant to write with le.com surrounded with asterisks

**Comment by kktt007** [comment]
i have solve the problem. Just add "." to the blacklist pattern(because white list is too much for us,), like : *.foo.com* , enough for me to cross the gfw, Thanks for the good job and swithomega on chrome.
