### ISSUE TITLE
Why is the "Access your data for all websites" permission required?

### ISSUE THREAD

**Issue by dirdi** [foxyproxy/firefox-extension#31]
With todays update FoxyProxy requests the "Access your data for all websites" permission. Please update the "About this extension" section on Firefox Add-ons (https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-basic/) and describe why this (formerly not needed) permission is required now.

**Comment by erosman** [comment]
The permission is needed in order to be able to delete browser data.

The permission was present in previous FoxyProxy up to 6.4
It was missed out in 6.5 & 6.6
It was re-added in 7.0

**Comment by ericjung** [comment]
If you look at the large eraser button, that is what deletes browser data and requires the permission.

**Comment by ericjung** [comment]
@dirdi, i don't see a permission called `Access your data for all websites`. These are what I see when installing:

![permissions](https://user-images.githubusercontent.com/5875610/65743017-fd97e680-e0af-11e9-8a2e-824de4b726e5.jpg)

If you're referring to `Clear recent browsing history, cookies, and related data`, that is already documented at https://addons.mozilla.org/en-US/developers/addon/foxyproxy-standard:

> "Clear recent browsing history, cookies, and related data": this is used by the big eraser button since version 6.3. You can delete cookies, cache, etc with one-click. A future version will allow you to clear the data automatically when switching proxies, just like the old FoxyProxy (pre-Firefox Quantum / Firefox 57).

If you're referring to a different permission, please re-open this bug and let me know.

**Comment by ericjung** [comment]
Hm, I'm not really sure what is causing that. The eraser button uses `Clear recent browsing history, cookies, and related data`. I think it is the `"<all_urls>"` in manifest.json, which is required to proxy any/all URLs. But that permission has been present since Firefox 57. Are you sure this is new?

**Comment by dirdi** [comment]
@ericjung yesterday I was asked by Firefox to grant this permission, but it may very well be the case that - for some reason - Firefox skipped a FoxyProxy version and the need for this permission was already introduced by an earlier version. Is there some "update log" I could provide?

However, my point is that this permission should be documented as the other required permissions are. An undocumented permission makes me feel queasy, especially if it is a permission that allows to grab "data for all websites", like credentials, bank balance etc.

Of course the even better option would be to decrement the number of needed permissions by dropping this permission and move erasing functionality to another plugin. Following the Unix philosophy "Do One Thing and Do It Well", I do not see the point why a proxy-management add-on should be responsible to erase browser data. Another add-on - maybe triggered by FoxyProxy - would be a cleaner approach.

**Comment by m-svo** [comment]
I found the information while looking at other extension.
They say that this permission comes from using the `proxy.onRequest` method.
If this is so, Mozilla lists this permission not because the extension actually gets your data for all websites, but because the extension has access to proxy settings and _potentially could get your data_ using their own proxy server.

**Comment by ericjung** [comment]
It's worth mentioning that FoxyProxy is a Mozilla recommended add-on and is 100% open source. If you have concerns that FoxyProxy might be stealing your data or gathering information about you in any way, please let me know. I can guide you through sections of the code to understand (if you are a programmer).

**Comment by ericjung** [comment]
Since this was added to https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-basic/

`Clear recent browsing history, cookies, and related data": this is used by the big eraser button since version 5.3. You can delete cookies, cache, etc with one-click`

I'm closing this ticket.

**Comment by dirdi** [comment]
@ericjung thank you for documenting the "Clear recent browsing history, cookies, and related data" permission. However, the "Access your data for all websites" permission remains not being documented and therefore I think this should not be closed, until this permission has either been removed or documented.

**Comment by erosman** [comment]
re: **Access your data for all websites**

FoxtProxy has to be able to proxify ALL URLs which requires `"<all_urls>"` permission.

Whenever, `"<all_urls>"` permission is used by an add-on, Firefox notice states "Access your data for all websites" which is a generalised notice and often appears more intrusive than what it really is.
I have personally brought up this problem to the AMO but there has been no change in the wording.

**In case of FoxyProxy, "Access your data for all websites" means to be able to proxy all URLs.**

It is worth noting that usually, `"<all_urls>"` permission by itself is not enough to "Access your data for all websites" and require other permissions.

For example` "cookie"` + `"<all_urls>"` permission would allow extension to access, read, write, delete cookies.

@ericjung 
The permission notices often cause concern for the users and that is why I always include a **Permissions Explanation** in all my add-on pages e.g. [FoxyTab](https://addons.mozilla.org/en-US/firefox/addon/foxytab/), [FireMonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/), etc
