### ISSUE TITLE
FoxyProxy Does Not Work With Firefox Nightly

### ISSUE THREAD

**Issue by shijialee** [foxyproxy/firefox-extension#39]
Hi, 

I am on the latest 7.3 version and My ssh tunnel has completely stopped working after the upgrade.

pattern:

```
{
  "mode": "patterns",
  "8nj921531846127435": {
    "title": "goog",
    "type": 3,
    "color": "#1609cc",
    "address": "127.0.0.1",
    "port": 1086,
    "proxyDNS": true,
    "active": true,
    "whitePatterns": [
      {
        "title": "all URLs",
        "active": true,
        "pattern": "*",
        "type": 1,
        "protocols": 1
      }
    ],
    "blackPatterns": [
      {
        "title": "local hostnames (usually no dots in the name). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "active": true,
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\\.\\d+\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1
      },
      {
        "title": "local subnets (IANA reserved address space). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "active": true,
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:192\\.168\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|172\\.(?:1[6789]|2[0-9]|3[01])\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1
      },
      {
        "title": "localhost - matches the local host optionally prefixed by a user:password authentication string and optionally suffixed by a port number. The entire local subnet (127.0.0.0/8) matches. Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "active": true,
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?[\\w-]+(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1
      },
      {
        "title": "baidu",
        "active": true,
        "pattern": "*.baidu.com",
        "type": 1,
        "protocols": 1
      },
      {
        "title": "example.com",
        "active": true,
        "pattern": "*.example.com",
        "type": 1,
        "protocols": 1
      }
    ],
    "index": 0
  },
  "logging": {
    "active": true,
    "maxSize": 500
  },
  "k20d21508277536715": {
    "title": "Default",
    "type": 5,
    "color": "#e54206",
    "active": true,
    "whitePatterns": [
      {
        "title": "all URLs",
        "active": true,
        "pattern": "*",
        "type": 1,
        "protocols": 1
      }
    ],
    "blackPatterns": [],
    "index": 1
  },
  "sync": true
}
```

Please help. Thanks.

**Comment by ericjung** [comment]
Hello,

1. Please confirm you have a SOCKS5 srver running on 127.0.0.1:1086  (i am guessing ssh -D ?)
2. What error do you se?
3. What does the FoxyProxy log say?

thank you.

**Comment by shijialee** [comment]
1. yes. running with ssh -CND
1. I do not see any error. I am running ssh debug mode `ss -v` too and there is no traffic going through. 
1. there is nothing in the log.

My original problem happened on work computer. 
I just upgrade firefox and foxyproxy to the latest on my home computer and experiencing the same problem.  And foxyproxy was working before the upgrade.

Both running Mac.

BTW, I notice that the foxyproxy icon doesn't change after switching from the proxy to `turn off (using firefox setting)`.  It was icon with a red cross in the previous version if I remember correctly.  see screenshot.


<img width="327" alt="Screen Shot 2019-09-29 at 11 58 13 PM" src="https://user-images.githubusercontent.com/652249/65835155-587e4780-e315-11e9-9373-344590d41adb.png">

**Comment by ericjung** [comment]
Hi

It sounds like there is a JavaScript error and I very much need your help to fix this. Do you know how to load an extension in debug mode and view the JavaScript console?

**Comment by shijialee** [comment]
I skimmed this page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging  and here are some console errors.  Please let me know what else I can do.

Also, When you say turn off FoxyProxy from the options page. Did you mean by choose from the dropdown from the options page? I did that and It has no effect. 

The first three errors are triggered when I clicked on the FoxyProx icon from Toolbar.

BTW, I am using Firefox Nightly.

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no] ExtensionCommon.jsm:75:12
    runSafeSyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:75
    cleanup resource://gre/modules/ExtensionContent.jsm:402
    close resource://gre/modules/ExtensionContent.jsm:929
    destroyed resource://gre/modules/ExtensionContent.jsm:1014
    observe resource://gre/modules/ExtensionContent.jsm:1032
sender.tab is undefined main.js:642
    onConnect moz-extension://70f40431-a2c4-054a-b979-96765fc88c37/background_scripts/main.js:642
    onConnect self-hosted:1021
    <anonymous> moz-extension://70f40431-a2c4-054a-b979-96765fc88c37/background_scripts/main.js:110
    apply self-hosted:2018
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2423
Promise resolved after context unloaded
2 utils.js:291
    monitorChromeStorage moz-extension://70f40431-a2c4-054a-b979-96765fc88c37/lib/utils.js:291
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:64
    <anonymous> moz-extension://30901ff7-057d-0541-b789-b8a9dc65fc59/background.js:64
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:72
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:72
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:64
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 10 background.js:1
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no] ExtensionCommon.jsm:75:12
sender.tab is undefined main.js:642
Promise resolved after context unloaded
2 utils.js:291
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:72
Empty string passed to getElementById(). FormAutofillHeuristics.jsm:383:22
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 3 background.js:64
browser.proxy.unregister is not a function 2 background.js:268
    setDisabled moz-extension://2d02daa1-50f9-e24f-a03a-43fc5e28216a/scripts/background.js:268
    sendToPAC moz-extension://2d02daa1-50f9-e24f-a03a-43fc5e28216a/scripts/background.js:181
    apply self-hosted:2018
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
    applySafeWithoutClone self-hosted:1023
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:808
browser.proxy.register is not a function background.js:229
    sendToPAC moz-extension://2d02daa1-50f9-e24f-a03a-43fc5e28216a/scripts/background.js:229
    apply self-hosted:2018
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
    applySafeWithoutClone self-hosted:1023
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:808
browser.proxy.unregister is not a function background.js:268
```

**Comment by shijialee** [comment]
FYI, I tried debug mode for another extension `colorzilla` which generated the following error like FoxyProxy. The extension is working fine though.

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no] ExtensionCommon.jsm:75:12
    runSafeSyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:75
    cleanup resource://gre/modules/ExtensionContent.jsm:402
    close resource://gre/modules/ExtensionContent.jsm:929
    destroyed resource://gre/modules/ExtensionContent.jsm:1014
    observe resource://gre/modules/ExtensionContent.jsm:1032
```

**Comment by ericjung** [comment]
Are you using Firefox Nightly? It is not supported yet. Please let me know.

**Comment by shijialee** [comment]
yes, I am using nightly.  I mentioned that 3 messages up. 

Well. Why the heck `check for update` pull the latest FoxyProxy in... 

Downgraded to 6.6.2 and works again.

**Comment by ericjung** [comment]
> Downgraded to 6.6.2 and works again.

That is strange. 6.6.2 also should not work with Nightly.

**Comment by rextheleopard** [comment]
FoxyProxy 7.3 does not works on nightly firefox builds.

**Comment by TriMoon** [comment]
I can confirm that 'FoxyProxy Standard Version: 7.3' **stopped** working on Nightly just a day or two ago....
It was working fine until that...

**Comment by ericjung** [comment]
I am aware that it does not work with Nightly. I am also aware of how to fix it, but have not finished the work yet. I have not supported Nightly in the past.

**Comment by mozbhearsum** [comment]
I'm hitting this in Nightly as well. I'm happy to help do any testing of any future builds, should that be useful.

**Comment by ericjung** [comment]
@mozbhearsum thank you that will be very helpful & I'll update this ticket when version is ready for testing with Nightly.

**Comment by ericjung** [comment]
This is fixed. I've done a lot of testing, but I have no finished all tests. If you'd like to try it:

You will not lose any settings.

1. Download and unzip [7.4 beta](https://github.com/foxyproxy/firefox-extension/archive/7.4.zip)
2. Enter `about:debugging#/runtime/this-firefox` in the Firefox URL bar
3. Click “Load Temporary Add-on”
4. Navigate to where you unzipped in step 1. Select any file in the `src` directory

Again, you will not lose any settings.

I would greatly appreciate any feedback. This also fixes issue https://github.com/foxyproxy/firefox-extension/issues/38.

**Comment by zao** [comment]
The 7.4 beta linked above seems to again select proxies, log URLs, and actually work, based on some brief testing in 64-bit Nightly on Win10.

**Comment by ericjung** [comment]
> The 7.4 beta linked above seems to again select proxies, log URLs, and actually work, based on 
> some brief testing in 64-bit Nightly on Win10.

Thank you -- anyone else have feedback please?

**Comment by mozbhearsum** [comment]
Works for me on the October 7th Nightly, too.

**Comment by bhzhu203** [comment]
> This is fixed. I've done a lot of testing, but I have no finished all tests. If you'd like to try it:
> 
> You will not lose any settings.
> 
>     1. Download and unzip [7.4 beta](https://github.com/foxyproxy/firefox-extension/archive/7.4.zip)
> 
>     2. Enter `about:debugging#/runtime/this-firefox` in the Firefox URL bar
> 
>     3. Click “Load Temporary Add-on”
> 
>     4. Navigate to where you unzipped in step 1. Select any file in the `src` directory
> 
> 
> Again, you will not lose any settings.
> 
> **I would greatly appreciate any feedback.** This also fixes issue #38.
> 
> Helping me to test this is how bugs are prevented! Please help.

Works in firefox Nightly !

**Comment by shijialee** [comment]
>     2\. about:debugging#/runtime/this-firefox

I am getting the following error:

```
There was an error during the temporary add-on installation.
Error details

File /Users/jfdi/Downloads/firefox-extension-7.4.zip does not contain a valid manifest
```

**Comment by shijialee** [comment]
> This is fixed. I've done a lot of testing, but I have no finished all tests. If you'd like to try it:
> 
> You will not lose any settings.
> 
>     1. Download and unzip [7.4 beta](https://github.com/foxyproxy/firefox-extension/archive/7.4.zip)
> 
>     2. Enter `about:debugging#/runtime/this-firefox` in the Firefox URL bar
> 
>     3. Click “Load Temporary Add-on”
> 
>     4. Navigate to where you unzipped in step 1. Select any file in the `src` directory
> 
> 
> Again, you will not lose any settings.
> 
> **I would greatly appreciate any feedback.** This also fixes issue #38.
> 
> Helping me to test this is how bugs are prevented! Please help.

works on October 7th Nightly for me. thanks!

**Comment by DjLegolas** [comment]
works on Nightly 71.0a1 (2019-10-10) (64-bit).
Great work @ericjung 👍

**Comment by sjuxax** [comment]
Firefox 71 hit the beta aka "Developer" channel yesterday and now the mainline FoxyProxy is totally dead for me. https://wiki.mozilla.org/Release_Management/Calendar is a little behind, but the ["99.99% up-to-date" Google Calendar link](https://calendar.google.com/calendar/embed?src=bW96aWxsYS5jb21fZGJxODRhbnI5aTh0Y25taGFiYXRzdHY1Y29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) from that page shows event named [DevEd 71.0b1 released @ 100%](https://calendar.google.com/calendar/r/week/2019/10/15?eid=MGQ2M3NkZDNwMzdocDI5c2ZkdDkxZXY5NjQgbW96aWxsYS5jb21fZGJxODRhbnI5aTh0Y25taGFiYXRzdHY1Y29AZw&ctz=America/Los_Angeles&sf=true) for 2019-10-15 (yesterday), so presumably this is going to start breaking for a lot more people soon.

I'm about to test the beta build, but if we're confident in these fixes, can we get this pushed to the official channels? @ericjung

**Comment by ericjung** [comment]
Yes, I'll get it out likely 2019-10-17 and Mozilla takes a day or two to approve. Basically I've been working on edge case testing this whole time.

Eric

**Comment by ericjung** [comment]
FoxyProxy 7.4 finished and submitted to Mozilla for approval. (Recommend Add-ons require manual review and approval by Mozilla before release, unlike non-recommended add-ons). I expect that to take 1-3 days.

Thanks, everyone, for your help debugging! This version is solid. I hope you like it.

**Comment by sjuxax** [comment]
Thanks for rushing this release out. It's been working well for me so far and it was delivered to my browser a couple of hours after your comment, so someone at Mozilla was probably paying attention. 

Really appreciate all the years of hard work you've put in to this project; it's been an indispensable tool for me for a long time. 🙇

**Comment by ericjung** [comment]
> Thanks for rushing this release out. It's been working well for me so far and it was delivered to my browser a couple of hours after your comment, so someone at Mozilla was probably paying attention.

Yay! I have worked for Mozilla 3 different times in the past and am on good terms with quite a few people still working there. I hope that helps.

> Really appreciate all the years of hard work you've put in to this project;

Thank you for noticing! I started FoxyProxy 13 years, and we will never separate. Just yesterday [I uploaded a huge archive of past releases,](https://github.com/foxyproxy/firefox-extension/tree/master/archive/dist/foxyproxy-standard) including 1.0 which was released in April 2006. Now I just have to upload the release notes, too. Maybe it's more appropriate for [archive.org](archive.org).

Anyway, the best way to help is to contribute by [donating](https://www.paypal.me/ericjung2/5.99) or [purchasing FoxyProxy VPN/proxy service](https://getfoxyproxy.org/order/). I don't push that in the software very much because I dont want to alienate people, but it is the reason I can continue to write this software. There are many reasons to choose FoxyProxy VPN/proxy service over competitors, but I dont want to push that on github. Ping me in email if you're interested (including a discount code).

> it's been an indispensable tool for me for a long time.

Thank you so much. This motivates me more than you can ever know.
