### ISSUE TITLE
Unable to enable "Add whitelist pattern to match all URLs" with SOCKS5

### ISSUE THREAD

**Issue by aaaaadrien** [foxyproxy/firefox-extension#43]
Hi,
Edition: FoxyProxy Standard
Version: 7.3
I create a SOCKS connection. I try to enable this 2 options :
- Add whitelist pattern to match all URLs
- Do not use for localhost and intranet/private IP addresses 
I set them on "ON" but after saving, options are on "OFF".
Impossible to USE SOCKS 5 on internet and keep the local connection for localnetworlks (10.0.0.0/8)

**Comment by ericjung** [comment]
You will not lose any settings.

Download and unzip 7.4 beta here: https://github.com/foxyproxy/firefox-extension/archive/7.4.zip

Enter about:debugging#/runtime/this-firefox in the Firefox URL bar

Click “Load Temporary Add-on”
Navigate to where you unzipped in step 1.

Select any file in the src directory


Again, you will not lose any settings.

Please let me know your results.

**Comment by aaaaadrien** [comment]
Hi, 
Done.
After update i only see "Send DNS through SOCKS5 proxy".
If i enable the socks all requests sent trough the socks5

**Comment by ericjung** [comment]
Yes, that's correct. After you add the proxy, those shortcuts for "whitelist all URLs" and "blacklist intranet/private IP addresses" are gone. If you want to edit patterns after creating the proxy,  please click the patterns button. If you expected something else, let me know but this is the way FoxyProxy has worked before. If it is confusing, please let me know. I can simply remove those two switches from the "add proxy" window.

**Comment by aaaaadrien** [comment]
I have, in pattern in the Black List a rule (enabled) which match with http://10.x.x.x/myapp. But when i tuen on SOCKS, unable to access to local http apps, but www.no-ip.com display the IP trough the SOCKS. So i am sure that the socks works.

**Comment by ericjung** [comment]
Hi

What is the exact pattern? And is it reg exp or wildcard?

**Comment by ericjung** [comment]
HI

Can you please export your FoxyProxy settings and upload the file here? Remove any private info first. The export is a text file (JSON) so open in a text editor to remove anything private.

**Comment by teonat** [comment]
I'm trying FoxyProxy for the first time today, and it seems like this is the issue I'm experiencing as well. 
The blacklist does not work at all when using a SOCKS5 proxy, neither with regex patterns nor wildcard.

**Comment by klamann** [comment]
Same issue here and I had a really hard time figuring it out. After I configured my SOCKS-proxy, of course I selected it from the dropdown menu to make it the active configuration and everything seemed to work as expected.

Some time later I noticed that my password manager (Keepass) didn't work anymore. Turns out that it communicates with Firefox over a local HTTP port and FoxyProxy was routing all local connections through the proxy. So I added the default "black patterns to prevent this proxy being used for localhost" - still no success. I checked the patterns against the integrated pattern tester, and they all seemed to be fine, except that I still couldn't access any local address.

Thanks to @teonat for pointing out the right setting to pick. It is far from intuitive that the blacklist doesn't work when you specifically select the proxy you want to use instead of the generic "Use Enabled Proxies By Patterns and Order".

I'm not sure how to improve the UX here, but the current solution is far from optimal.

**Comment by ericjung** [comment]
The app used to say:

* Use Enabled Proxies by Patterns and Order
* Proxy A (Ignore patterns and order)
* Proxy B (Ignore patterns and order)
* Proxy C (Ignore patterns and order)
* Turn off (Use Firefox Settings)

Proxy A, B, C are just examples names -- the key point is *Ignore patterns and order* was in the user interface and it is not anymore.

@klamann would that have helped you?

**Comment by klamann** [comment]
@ericjung that would probably have helped to notice that I wasn't doing it right when I selected the proxy in the first place.

Furthermore, it might be helpful to show some advice on the patterns page that the patterns will not apply, as long as "Use Enabled Proxies By Patterns and Order" is not selected. Maybe only show that message when this option is *not* selected and give the user an easy way to switch to that option (e.g. by clicking a button and not by describing how to get to that dropdown menu and then to make the right selection).

**Comment by ericjung** [comment]
@klamann thanks for the feedback.

> it might be helpful to show some advice on the patterns page that the patterns will not apply,
> as long as "Use Enabled Proxies By Patterns and Order" is not selected. 

Uh.... that's already there:

![it-is-already-there](https://user-images.githubusercontent.com/5875610/75488142-03e70300-596d-11ea-8aef-157f447889d6.jpg)

Why did you miss it? Should it be flashing red instead?

**Comment by klamann** [comment]
you're right, I didn't notice that at all o.O
Not sure why though... seems like I was so focused on the black patterns that I didn't bother to read it.

Maybe some context-sensitive notification would be more effective? Like when *Use Enabled Proxies By Patterns and Order* is not active and you edit the patterns or you click save, a message appears that warns you that what you're doing right now won't have any effect unless you change the mode you're in. But I'm just guessing here, I'm not experienced with UI stuff ;)

**Comment by erosman** [comment]
The process is completely redesigned in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should eliminate the issue.
