### ISSUE TITLE
There is no option for enabling proxy by pattern

### ISSUE THREAD

**Issue by rezatorabi** [foxyproxy/firefox-extension#49]
The options "Use Enabled Proxies By Pattern and Priority" or "ignore patterns" don't exist for me.
This is how I think it is supposed to be:
![options](https://user-images.githubusercontent.com/9264258/68657148-60521e00-0548-11ea-85b5-613026ef74f7.PNG)

And this is what I have:
![foxyproxy](https://user-images.githubusercontent.com/9264258/68657735-81ffd500-0549-11ea-8d14-6f8e166ad41d.png)

I am using FoxyProxy Standard version 7.4.1 in Firefox 70.0.1 on Ubuntu 18.04.

**Comment by ericjung** [comment]
Hi

This happens when you don't have any whitelist patterns defined. It is confusing and I will remove it in the next release. The idea is that without whitelist patterns, there is no reason to put FoxyProxy into patterns mode... No URLs will ever match.

Anyway, for now, please add a whitelist pattern (even just *) and you'll see that option.

**Comment by rezatorabi** [comment]
Thanks for the fast response. It is working now.

Maybe it would be more straightforward if the "* whitelist pattern" existed by default. (It is usually how the user expects it to be that if he doesn't define any whitelist pattern and only defines blacklist pattern, he wants it so that everything except the defined blacklist are proxied and if he only defines whitelist pattern and no blacklist pattern I want nothing to be proxied except the defined whitelist). I think using whitelists and blacklists at the same time doesn't make much sense to me and is not a common usecase.

**Comment by rezatorabi** [comment]
Hi,
Thanks for the fast response. It is working now.

Maybe it would be more straightforward if the "* whitelist pattern" existed by default. (It is usually how the user expects it to be that if he doesn't define any whitelist pattern and only defines blacklist pattern, he wants it so that everything except the defined blacklist are proxied and if he only defines whitelist pattern and no blacklist pattern I want nothing to be proxied except the defined whitelist). I think using whitelists and blacklists at the same time doesn't make much sense to me and is not a common usecase.

**Comment by ericjung** [comment]
> Maybe it would be more straightforward if the "* whitelist pattern" existed by default.

Agreed. When adding a new proxy, **Add whitelist pattern to match all URLs** should be ON by default. Currently it is OFF by default. I will change this.

![fp-999](https://user-images.githubusercontent.com/5875610/68774940-03f40a80-05eb-11ea-97ae-66fe71eb3103.jpg)

**Comment by rezatorabi** [comment]
That would be great.

Thanks a lot for maintaining this useful add-on.
