### ISSUE TITLE
Pattern not working as expected

### ISSUE THREAD

**Issue by bendeguz-szatmari** [foxyproxy/firefox-extension#54]
Hi!

Edition: FoxyProxy Standard
Version: 7.4.2
Platform: Windows 10

I have opened an SSH tunnel to a server on port 10000 with Putty. I would like to access a remote website through the tunnel by IP address. Proxy configuration: SOCKS5 on localhost:10000.
Working scenario:
- Set to use proxy "for all URLs"
- Open website over HTTPS, for example: https://1.1.1.1/requested-path -> opened

Not working scenario:
- Create white pattern: 1.1.1.1 (pattern test passed, however it ignores paths)
- Set "Use Enabled Proxies By Patterns and Order"
- Open website over HTTPS, for example: https://1.1.1.1/requested-path -> unable to connect
- The proxy is working with other white patterns, like *.mydomain.com

Am I missing something or the pattern is wrong?

**Comment by alexmgr** [comment]
@bendeguz-szatmari, same issue here (FF 71, foxyproxy 7.4.2). I think IP based matching doesn't work post FF 71 upgrade? or at least that's when I started noticing.
FWIW, pattern-tester returns a positive match (e.g: http://1.1.1.1/foo with a whitelist of 1.1.1.1 returns a match)

**Comment by ericjung** [comment]
The pattern tester logic is identical to the real-time url matching, so if one matches but not the other, I'm very surprised. I'll look at this more closely.

**Comment by ericjung** [comment]
I cannot reproduce this. Can you please export your settings in FoxyProxy and attach them here?  Click the *Export* link on the main FoxyProxy page. It creates a JSON file. You can open this JSON file in a text editor and remove all private info before posting it. You can also just export the patterns on the *Edit Patterns* page, but I'd rather have the entire JSON export because I can then simulate your exact environment using same proxy type and port.

For what it's worth, https://1.1.1.1/ will always generate a certificate warning in Firefox because SSL certificates are signed against domain names, not IP addresses. That should not affect URL pattern matching, however. Just accept the warning and continue.

Thanks for your export and reporting the bug!

**Comment by ericjung** [comment]
Anyone?

**Comment by bendeguz-szatmari** [comment]
Sorry for the late reply. Here is my configuration,  the "app-prod" filter is the problematic one ( I have removed the real addresses):
{
  "t6ejl1576667345126": {
    "type": 3,
    "color": "#66cc66",
    "title": "proxy",
    "active": true,
    "address": "127.0.0.1",
    "port": 10000,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "whitePatterns": [
      {
        "title": "mydomain",
        "pattern": "*.mydomain.com",
        "type": 1,
        "protocols": 1,
        "active": true
      },
      {
        "title": "site",
        "pattern": "site.mydomain.com:5000",
        "type": 1,
        "protocols": 1,
        "active": true
      },
      {
        "title": "app-prod",
        "pattern": "1.1.1.1",
        "type": 1,
        "protocols": 4,
        "active": true
      }
    ],
    "blackPatterns": [
      {
        "title": "local hostnames (usually no dots in the name). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\\.\\d+\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true
      },
      {
        "title": "local subnets (IANA reserved address space). Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:192\\.168\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|172\\.(?:1[6789]|2[0-9]|3[01])\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true
      },
      {
        "title": "localhost - matches the local host optionally prefixed by a user:password authentication string and optionally suffixed by a port number. The entire local subnet (127.0.0.0/8) matches. Pattern exists because 'Do not use this proxy for localhost and intranet/private IP addresses' is checked.",
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?[\\w-]+(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true
      }
    ],
    "pacURL": "",
    "index": 9007199254740990
  },
  "mode": "patterns",
  "logging": {
    "size": 100,
    "active": true
  },
  "browserVersion": "71.0",
  "foxyProxyVersion": "7.4.2",
  "foxyProxyEdition": "standard",
  "sync": true
}

**Comment by ericjung** [comment]
@bendeguz-szatmari thank you. Some questions:

1. Are you really trying to hit a web server at 1.1.1.1 or is that just an IP address you replaced with the actual address for privacy reasons?
2. Is the web server on an address only accessible over intranet or is it accessible over the public internet?
3. Is your SOCKS server hosted on an intranet or is it accessible over the public internet?
4. Are you using username/password authentication with the SOCKS server or is there no auth?

thanks,
eric

**Comment by bendeguz-szatmari** [comment]
Hi,

1. No, I just replaced the real IP.
2. I am accessing the web server over intranet (VPN), it is not public. 
3. The SOCKS server is hosted on my machine, PuTTY does the work for me, like [this](http://support.moonpoint.com/network/proxy/putty/). 
4. There is no authentication for the proxy.

**Comment by ericjung** [comment]
@bendeguz-szatmari thanks for the info. You need to delete the blacklist patterns. One of them is matching your web server IP address and, since black patterns take precedence over white patterns, the website is not loaded through your proxy server.

**Comment by bendeguz-szatmari** [comment]
@ericjung Thanks for your help. Deactivating the "local subnets" pattern solved the issue (the webserver is in 10.x.x.x sub).
