### ISSUE TITLE
Local and intranet IP address patterns: are they correct?

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#56]
Received via email:

Hello,

I mainly use v.4.6.5 in Palemoon and was surprised to see different regexps for "local IPs" in v, 7.4.1 for Firefox. Checking further, I come to the conclusion that they are wrong:

A pattern that only contains '[\w-]+' (words and a 'minus') for the hostname will not match a string like 127.0.0.1 - and the 'pattern test' clearly shows that! You must change the third pattern from

`^https?://(?:[^:@/]+(?::[^@/]+)?@)?[\w-]+(?::\d+)?(?:/.*)?$`

to

`^(?:[^:@/]+(?::[^@/]+)?@)?(?:[\w-]+|127\.\d+\.\d+\.\d+)(?::\d+)?(?:/.*)?$`

Further, in 4.x there was a pattern

`^https?://185\.39\.10\..*$`

that I miss in the local IP patterns of 7.4.1.

FYI I use it in Firefox under Linux.

Thank you for the huge effort you have put into this whole project!

**Comment by ericjung** [comment]
You wrote there was a pattern in 4.6.2:

`^https?://185\.39\.10\..*$`

But that is not a local IP address. Are you certain it is there?

2 You wrote this pattern does not match 127.0.0.1 :

`^https?://(?:[^:@/]+(?::[^@/]+)?@)?[\w-]+(?::\d+)?(?:/.*)?$`

But I do not see that pattern in 7.4.1 or 7.4.2. Where did you get it?

I do see this pattern, which matches 127.0.0.1:

`^(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\.\d+\.\d+\.\d+)(?::\d+)?(?:/.*)?$`

**Comment by erosman** [comment]
Patterns process is re-written in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should fix this issue.

Note:
`127\.\d+\.\d+\.\d+` will match `127.0.0.1` as well as the entire `127.*.*.*` range i.e `127.0.0.0/8`.

**Comment by ericjung** [comment]
This was never an issue. The person who opened the ticket reported patterns that do not exist, and did not reply here.
