### ISSUE TITLE
Leaks IP on Firefox startup

### ISSUE THREAD

**Issue by Hakkin** [foxyproxy/firefox-extension#57]
If you have your Firefox set to save your session on shutdown, in certain cases when you reopen Firefox, the proxy will not be enabled immediately and your real IP will leak to the initial pages that open.

Steps to reproduce:
1. Make sure "Restore previous session" is checked in Firefox options.
2. Have a proxy enable in FoxyProxy.
3. Open a page like https://www.whatsmyip.org/ in a new tab.
4. Clear the Firefox cache (Privacy & Security -> Clear Data -> Cached Web Content) so this page will be rerequested on startup.
5. Navigate back to the tab in (3).
6. Exit Firefox.
7. Reopen Firefox.
8. Website should list real IP rather than Proxy IP.

**Comment by ericjung** [comment]
Hi,

Thanks for the bug report, but this is a Firefox bug affecting many add-ons, not just FoxyProxy. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1501159

**Comment by Hakkin** [comment]
> 
> 
> Hi,
> 
> Thanks for the bug report, but this is a Firefox bug affecting many add-ons, not just FoxyProxy. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1501159
> 
> FoxyProxy cannot fix this problem, unfortunately.
> 
> For what it's worth, this was not a bug before Firefox 57 (Quantum).

The bug you linked is marked as a duplicate of a bug that is already fixed. Is Mozilla aware that this is still an issue?

**Comment by ericjung** [comment]
> The bug you linked is marked as a duplicate of a bug that is already fixed.

You must be talking about https://bugzilla.mozilla.org/show_bug.cgi?id=1447551. It does not allow proxy add-ons to block network requests until the proxy add-on is ready. By 'ready', I mean: add-on is loaded and has registered its handlers, and the add-on has had the chance to load its settings from disk or sync server.

>  Is Mozilla aware that this is still an issue?

I do not know; I would review those two tickets. However, I doubt Mozilla will allow the behavior that is needed to really solve this. It would mean Firefox start-up time would suffer, and in recent years start-up time has become a very sensitive, key metric for all browsers, not just Firefox.

You might get better results if you ensure that *Synchronize Settings * in FoxyProxy is off. However, this won't eliminate the problem. It will just ensure that your settings are loaded faster.
