### ISSUE TITLE
Log file ignores "log limit"

### ISSUE THREAD

**Issue by leapmotiondev** [foxyproxy/firefox-extension#58]
As the title says, the log file/list is ignoring the limit making my firefox freeze for about a minute when i navigate to the log page.

Has anyone else the same issue?

Screenshot: https://f.xize.icu/7bc5b/JoHaQoye40.png

**Comment by ericjung** [comment]
Confirmed. This bug was introduced in 7.4.2. I will fix it shortly.

**Comment by ericjung** [comment]
released with 7.4.3.
