### ISSUE TITLE
Proxy name and address widths are too small

### ISSUE THREAD

**Issue by Stolka** [foxyproxy/firefox-extension#62]
Hi,

I find proxy name and address widths are too small, I usually put provider name and proxy location as name. But since it's too small, I can't tell which proxy I'm gonna edit or delete.

Screenshot: [https://i.imgur.com/bawxNyd.png](https://i.imgur.com/bawxNyd.png)

Thanks!

**Comment by ericjung** [comment]
thanks for the screenshot and report. i will work on it.
