### ISSUE TITLE
Send DNS through SOCKS5 proxy dont work!

### ISSUE THREAD

**Issue by bug-repport** [foxyproxy/firefox-extension#63]
Hello, thanks for FoxyProxy its the best! :)

Send DNS through SOCKS5 proxy dont work my configuration!

I'am use Tor Browser without tor, manual, edit about:config:
```
extensions.torlauncher.start_tor;false
network.proxy.socks;10.1**.0.3 (My proxy)
network.proxy.socks_port;1080 (My port)
extensions.torbutton.use_nontor_proxy;true
```

my confiration proxyfoxy (proxy 10.1**.0.1):
https://i.postimg.cc/1t0BBxRQ/2020-01-24-103018.jpg
https://i.postimg.cc/dt3RkZCv/2020-01-24-103130.jpg
https://i.postimg.cc/3RL4Y9nG/2020-01-24-103407.jpg
https://i.postimg.cc/rmpsnxMw/2020-01-24-103509.jpg

tests for site (whatleaks.com, browserleaks.com):
https://i.postimg.cc/5t9fbzjd/2020-01-24-103915.jpg
https://i.postimg.cc/PrmHDywn/2020-01-24-104427.jpg

DNS is leaked! Please fix it!

**Comment by bug-repport** [comment]
Solved, add pattern *browserleaks.*

**Comment by ericjung** [comment]
Follow-up (user sent messages outside of github): he had patterns missing for other domains used by browserleaks and another leak test site.
