### ISSUE TITLE
sock5 proxy not work in Android Firefox 68.3.0

### ISSUE THREAD

**Issue by stzdzyhs** [foxyproxy/firefox-extension#65]
First, Great thanks for this very useful Extension.
I test this in the PC Firefox, it works fine. however, if install in the Android Firefox, sock5 proxy not work.(the browser progress bar stop at about 20%.)
I checked the code, and it seems that it's not necessary store the settings in the local and sync --- the two diff storage area, and I suspect that the stop is in the certain async-await code block. 
If you agree, I will submit a pull request and only use local storage, (the only complex is, the "pattern" proxy match, because I don't have http/https proxy for testing...).
Any suggestion? And Thank you very much !

**Comment by ericjung** [comment]
I do not believe socks proxies work on Android with Firefox at all. Try removing FoxyProxy and configure Firefox to use a socks proxy — I would guess it does not work. Please let me know.

**Comment by stzdzyhs** [comment]
The problem is, my sock5 proxy needs user/password auth, and the Firefox(Android and PC) does not support user/passwd auth, Firefox can only use sock5 proxy without any auth.
actually, I tried this: directly return sock5 proxy info in the proxyOnRequest event handler, that's background.js function proxyRequest(), Android Firefox works !

**Comment by WhinVader** [comment]
If u need use socks5 proxy with auth on android u can use adguard adblock, that app have ability to setup sock5 proxy with auth.

In addition, I have my own very stupid user question, I believe it is not worthy of a separate topic, so I will ask it here, please explain the purpose of the on/off button, which is located to the right of the green lock icon (which as I understand it is an indicator that a proxy with authorization).
![1](https://user-images.githubusercontent.com/60768503/74002658-df58c600-4980-11ea-83d9-6fed49dfaed8.png)

**Comment by stzdzyhs** [comment]
@WhinVader Thanks your suggestion, but a good user experience is,  if possible, use the same software, and Android Firefox really support it in Extension interface.
If I understand right, that on/off button is used when selection is "Use Enabled Proxies By Pattern and Order" (only standard edition has this option, basic edition without it), 
The extension will match proxy by URL only for "enabled"  proxies.
Regards

**Comment by ericjung** [comment]
`please explain the purpose of the on/off button, which is located to the right of the green lock icon (which as I understand it is an indicator that a proxy with authorization).`

@stzdzyhs is correct. If you select **off**, then that proxy is not used in mode  **Use Enabled Proxies By Pattern and Order** If you are using FoxyProxy Basic, that option makes no sense and I need to remove it.

**Comment by erosman** [comment]
In FoxyProxy v8, the on/off button will disable the proxy:
- it will not be used in proxies by pattern
- it will be disabled (or maybe removed, not decided yet) in the toolbar pop-up so it cant be selected

The purpose is to allow users to temporary disable a proxy and its associated patterns (if any) for testing or finding out issues.
