### ISSUE TITLE
Huge memory leak if proxy is unresponsive

### ISSUE THREAD

**Issue by WhiteExponent** [foxyproxy/firefox-extension#67]
Hello. I am using Shadowsocks + Cloak to hide my internet connection from censorship. I can use this with many programs fine, and I use FoxyProxy with firefox to route to this proxy locally. However, when my local proxy times out or I accidentally plug the internet off, Firefox does the following things:

1. Unresponsive to tab switches, JavaScript stops working
2. Hovering over works, but the mouse cursor doesn't change at all and scrolling is not possible
3. Firefox starts gaining memory at about 70MB/s

I usually leave my computer on when I go to work, and sometimes I come back to find that Firefox has taken up so much memory that it caused me to swap over 2GB, and eventually Firefox itself died. This only happens when FoxyProxy is enabled. How can I debug this issue?

FoxyProxy version: 7.4.3
Firefox version: 72.0.2, but this has been happening since *at least* Firefox 65.

**Comment by WhiteExponent** [comment]
Additionally, once the proxy is restarted or resumes working again, Firefox slowly drains this gained memory at about 50MB/s, and the mouse cursor flashes rapidly between different cursors, i.e. if I hovered over a link while the memory leak was happening, it would flash to the "hand" cursor for a split second, before going back to normal. It seems to me like some "queue" is filling up inside Firefox which then empties out once the proxy connection is restored.

**Comment by ericjung** [comment]
I think this is due to the way proxy username/password is being managed in FoxyProxy. AAre you using a username/password for your shadowsocks + cloak? (if it's running on localhost then this is unlikely, but please let me know anyway).

**Comment by erosman** [comment]
Authentication process is re-written in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should fix this issue.

**Comment by ericjung** [comment]
User never replied. I don’t think the issue was related to FoxyProxy. No one else ever complained about this and I could not reproduce it.
