### ISSUE TITLE
Fallback to Firefox settings if proxy is unreachable 

### ISSUE THREAD

**Issue by simmis** [foxyproxy/firefox-extension#68]
I have Foxyproxy configured to use a proxy that is listening on localhost. When the port is unreachable (proxy down), I was surprised to find that, after a short delay of a couple of seconds, it still retrieves the pages through the regular connection. This is potentially a privacy concern. 

When instead, I use the Firefox settings to point at my localhost proxy, stop the proxy and try to retrieve a page, I do get a "Proxy unavailable" error message from Firefox. This would be the expected behaviour with Foxyproxy as well. 

Can anyone confirm this?

**Comment by dud1337** [comment]
That doesn't happen for me if the proxy is down. Using FoxyProxy Standard and FireFox 68.5.0esr (64-bit)

Error image:
![burp](https://user-images.githubusercontent.com/5631021/76428642-3a317300-63ae-11ea-887b-d86aa25c0d3a.png)

**Comment by ericjung** [comment]
Thanks for the comment, @dud1337. I also don’t see this problem. Maybe @simmis can share his settings by exporting them and pasting here so I can try to reproduce. He doesn’t even mention what kind of proxy server he’s using.
