### ISSUE TITLE
Proxy does not work in Android

### ISSUE THREAD

**Issue by tkzv** [foxyproxy/firefox-extension#69]
Firefox version 68.4.2. Standard addon .

I enter a proxy IP and port, set either "*" or "getfoxyproxy.org" pattern, open https://getfoxyproxy.org/geoip/ and it displays my real IP.

**Comment by ericjung** [comment]
This is a bug with Firefox on Android. Please open a ticket at bugzilla.mozilla.org about proxy support on Android.
