### ISSUE TITLE
Plugin did not work correctly in view-source

### ISSUE THREAD

**Issue by tamquanminh** [foxyproxy/firefox-extension#70]
in view-source mode, plugin did not work correctly

![2020-02-21_21-58-05](https://user-images.githubusercontent.com/58721688/75045347-b3e3e880-54f5-11ea-97d1-3e6adffd71f7.png)

**Comment by ericjung** [comment]
This is a Firefox bug, not FoxyProxy. There is a bug for it on https://bugzilla.mozilla.org but I cannot find it at the moment. It's been open for 2 or more years.
