### ISSUE TITLE
Pop-up window "Authentication Required - Mozzilla Firefox"

### ISSUE THREAD

**Issue by vpistillo** [foxyproxy/firefox-extension#72]
With last version if in a foxyproxy profile we define a proxy with authentication, it doesn't appear the pop-up window of "Authentication Required" then if you close the browser the pop-up windows appear.

**Comment by ericjung** [comment]
The pop-up appears when you close Firefox? I need your exported foxyproxy settings. This continues version information and proxy type and mode, which you did not include in your bug report.

**Comment by vpistillo** [comment]
This is my file settings, some part have been anonymized:
[FoxyProxy Standard_2020-03-26.json.txt](https://github.com/foxyproxy/firefox-extension/files/4385635/FoxyProxy.Standard_2020-03-26.json.txt)

**Comment by ericjung** [comment]
Is the pop-up coming just after Firefox starts? If so, it is happening because FoxyProxy has loaded but has not had time to load info from storage. Can you try turning OFF Synchronize Settings? 

![image](https://user-images.githubusercontent.com/5875610/77673035-42adb000-6f4f-11ea-98c1-abe014987be3.png)

**Comment by vpistillo** [comment]
The behavior has remained the same. The pop-up coming just after Firefox has been closed.

**Comment by ericjung** [comment]
Hi,

Firefox was loading something when it closed. There is another process (addon or Firefox) that run on shut-down to report something. Are you using patterns or one proxy directly? Which version of Firefox? Is Firefox telemetry on? Please try this on a new, clean Firefox profile without any other extensions -- and not nightly or beta Firefox.

**Comment by vpistillo** [comment]
Sorry for the late. Hi follow your suggestion and now works.
