### ISSUE TITLE
Proxy DNS name not passed through proxy

### ISSUE THREAD

**Issue by vdot0x23** [foxyproxy/firefox-extension#73]
I have set up proxy a:
```json
    "type": 3,
    "color": "#b5aacc",
    "title": "a",
    "active": true,
    "address": "localhost",
    "port": 1338,
    "proxyDNS": true,
    "username": "",
    "password": "",
    "whitePatterns": [
      {
        "title": "a pattern 1",
        "pattern": "*localhost.example.org*",
        "type": 1,
        "protocols": 1,
        "active": true
      }
    ],
    "blackPatterns": [],
    "pacURL": "",
    "index": 0
```

Alongside proxy b: 
```json
    "type": 1,
    "color": "#ccc977",
    "title": "a",
    "active": true,
    "address": "localhost.example.org",
    "port": 4444,
    "proxyDNS": false,
    "username": "",
    "password": "",
    "whitePatterns": [
      {
        "title": "all URLs",
        "pattern": "*.mytld",
        "type": 1,
        "protocols": 1,
        "active": true
      }
    ],
    "blackPatterns": [],
    "pacURL": "",
    "index": 1
```

# Expected behavior

Whenever proxy b matches, i would expect the address, `localhost.example.org` to match the rule in proxy a, resulting in the following traffic flow.

firefox --> localhost:1338 --> localhost.example.org:4444 --> destination

# Actual behavior

Traffic flows like shown below (Wireshark).

firefox --> localhost:4444

**Comment by ericjung** [comment]
Hi,

That's not how FoxyProxy works. When a white pattern in proxy B matches a loading URL, then the proxy defined in B is used to load that URL (in your case,  localhost.example.org:4444).

This is pretty clear, with examples, if you read any of the docs I've written.

It looks like you are trying to chain proxies together. If that's true, you'll have to configure the intermediary proxy to do that. FoxyProxy can't.

**Comment by vdot0x23** [comment]
Hi again,

I obviously couldn't find it in the docs (and still can't), but I am not complaining, FoxyProxy is great :)
