### ISSUE TITLE
[Feature Request] Support for GFWlist?

### ISSUE THREAD

**Issue by Daymond** [foxyproxy/firefox-extension#74]
Is there any possibility to support GFWlist?

**Comment by ericjung** [comment]
Yes, I can add support for that.

**Comment by Daymond** [comment]
> Yes, I can add support for that.

Thanks so much.

**Comment by woosley** [comment]
Hi, I think what is needed is a common way to import whitelist pattern from url/file.

**Comment by ericjung** [comment]
Yes, I agree. There is another feature request for this. Old FoxyProxy (pre Firefox-57) had this feature. I will add it again, but accept pull requests for help.

**Comment by 117649** [comment]
@ericjung It has been a year now. Any light on this?

**Comment by ericjung** [comment]
Not yet, but as I said, I will accept merge  requests for it.

**Comment by erosman** [comment]
Looking at one GFWlist, it has 8400+ rules.


- Pages often make 100+ of net connections (for each of its components e.g. images, CSS, etc) and checking against 8400+ rules for each of the net connection can slow down page loading and create  unwanted load on CPU & RAM
- From personal experience, most users may only need or use 100 of those rules therefore including 8400+ rules that contains sites that might never be visited is not efficient
- Creating/displaying 8400+ rules will slow down the UI

**Comment by 20NE** [comment]
Never mind, firefox already supports PAC file.

**Comment by erosman** [comment]
> Never mind, firefox already supports PAC file.

PAC is also supported in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

**Comment by ericjung** [comment]
@erosman i don’t see GWList as a PAC file anywhere. How is PAC related to this?

**Comment by erosman** [comment]
I didn't search for GWList PAC but I assumed it is available based on the previous post and the fact that it is possible to make a PAC based on GWList.
The URL for such PAC then can be entered as PAC URL in FoxyProxy v8.0

**Comment by ericjung** [comment]
Looks like it is here:
https://github.com/petronny/gfwlist2pac
