### ISSUE TITLE
FoxyProxy doesn't import settings

### ISSUE THREAD

**Issue by victormazevedo** [foxyproxy/firefox-extension#76]
Hello! First, I want to thank you for the great job building foxyproxy!
How the title says, I can't import any .xml file settings to FoxyProxy. I'm using Firefox 75 and FoxyProxy 7.4.3.
When I select the .xml file that I want to import, I receive this message: `This will overwrite existing proxy settings. Are you sure?`
I click in "Ok" and after that I just see a symbol of loading and nothing happens. I don't know if I'm doing something wrong, but I tested in two different machines and the same problem occurs.
Thanks!

**Comment by ericjung** [comment]
Hello Victor,

1. Where did you get the XML file? Please note that FoxyProxy has not used XML format in almost 3 years (since before Firefox Quantum in November 2017).
2. Can you post the XML here?

Thanks,
Eric

**Comment by victormazevedo** [comment]
Hello Eric,

   1. I did get the XML file in Amazon Web Services. I was studying EMR service and to enable web connection I followed AWS instuctions.
   2.This is the XML: 
```<?xml version="1.0" encoding="UTF-8"?>
<foxyproxy>
    <proxies>
        <proxy name="emr-socks-proxy" id="2322596116" notes="" fromSubscription="false" enabled="true" mode="manual" selectedTabIndex="2" lastresort="false" animatedIcons="true" includeInCycle="true" color="#0055E5" proxyDNS="true" noInternalIPs="false" autoconfMode="pac" clearCacheBeforeUse="false" disableCache="false" clearCookiesBeforeUse="false" rejectCookies="false">
            <matches>
                <match enabled="true" name="*ec2*.amazonaws.com*" pattern="*ec2*.amazonaws.com*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*ec2*.compute*" pattern="*ec2*.compute*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="10.*" pattern="http://10.*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*10*.amazonaws.com*" pattern="*10*.amazonaws.com*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*10*.compute*" pattern="*10*.compute*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*.compute.internal*" pattern="*.compute.internal*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*.ec2.internal*" pattern="*.ec2.internal*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
            </matches>
            <manualconf host="localhost" port="8157" socksversion="5" isSocks="true" username="" password="" domain="" />
        </proxy>
    </proxies>
</foxyproxy>
```
Thanks!

**Comment by ericjung** [comment]
Hello Victor,

Change `lastresort="false"` to `lastresort="true"`, save file, and then import again. Here it is:

```
<foxyproxy>
    <proxies>
        <proxy name="emr-socks-proxy" id="2322596116" notes="" fromSubscription="false" enabled="true" mode="manual" selectedTabIndex="2" lastresort="true" animatedIcons="true" includeInCycle="true" color="#0055E5" proxyDNS="true" noInternalIPs="false" autoconfMode="pac" clearCacheBeforeUse="false" disableCache="false" clearCookiesBeforeUse="false" rejectCookies="false" >
            <matches>
                <match enabled="true" name="*ec2*.amazonaws.com*" pattern="*ec2*.amazonaws.com*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*ec2*.compute*" pattern="*ec2*.compute*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="10.*" pattern="10.*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*10*.amazonaws.com*" pattern="*10*.amazonaws.com*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*10*.compute*" pattern="*10*.compute*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*.compute.internal*" pattern="*.compute.internal*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
                <match enabled="true" name="*.ec2.internal*" pattern="*.ec2.internal*" isRegEx="false" isBlackList="false" isMultiLine="false" caseSensitive="false" fromSubscription="false" />
            </matches>
            <manualconf host="localhost" port="8157" socksversion="5" isSocks="true" username="" password="" domain="" />
        </proxy>
    </proxies>
</foxyproxy>
```

Please note: I did not actually test the patterns. But I did change one of them from `http://10.*` to `10.*` so that it works with both `http` and `https`.

**Comment by victormazevedo** [comment]
Hello Eric!

With this work around it worked! Another way that I tried here was in Chrome and worked too.

Thank you very much for your help!

**Comment by nawa** [comment]
I have the same error working with AWS
It is definitely because of `lastresort=false`, browser console shows
```
ReferenceError: LASTRESORT is not defined
	import.js:289:27
```

**Comment by ericjung** [comment]
@nawa were you able to work around the problem with the instructions in this thread?

**Comment by nawa** [comment]
@ericjung Yes, it works. Thanks

**Comment by jacobus** [comment]
@ericjung Thanks for the great extension.

I also have the problem. The settings example from AWS is located here in there documentation:

https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-connect-master-node-proxy.html

We could update the docs and create a pull request
https://github.com/awsdocs/amazon-emr-management-guide/blob/master/doc_source/emr-connect-master-node-proxy.md

But it may break it for Chrome users. Not sure what you would like to do, but thousands of users will run into this problem at some stage. These docs form parts of the machine learning courses and for users of AWS in general.

Kind regards,
Jack

**Comment by ericjung** [comment]
@jacobus , I will release a new version this weekend with the fix. Then it will take Mozilla few days to a week to approve it. Is that fast enough? If not, I can make the documentation pull request you suggest...

Eric

**Comment by jacobus** [comment]
That would be great. Thank you!

**Comment by mallory98e** [comment]
> Hello Victor,

Dude I don't know where u living but my Firefox just decided this year to trash all my foxyproxy settings. It was working so far. foxyproxy.xml cannot be imported with the legacy import I keep getting unsupported file format...

Like why on earth to change something which worked for 10 years and if you do why trash the old one. After struggling with this for hours I decided I open the settings file in gedit and manually readd all my proxies.

Big f midfinger.
