### ISSUE TITLE
Settings synchronization doesn't work unless you add at least one proxy

### ISSUE THREAD

**Issue by ConMak** [foxyproxy/firefox-extension#77]
Hi! I am currently using the latest version of Firefox (75.0) on all my devices but the settings synchronization doesn't work unless you add at least one proxy to be able to toggle "Synchronize Settings" button on, because this button is missing. Without doing so the settings synchronization doesn't work and it is not obvious why.

**Comment by ericjung** [comment]
The button is missing when there are no proxies because there is nothing to synchronize.

**Comment by ConMak** [comment]
> The button is missing when there are no proxies because there is nothing to synchronize.

But what if I have everything configured on another device and just want these settings to be synced on my other devices? The Firefox "Sync Settings" button don't do anything unless you add at least one "stub" proxy to get the proxy settings synced

**Comment by ConMak** [comment]
I've just tested it again and the proxy settings synced correctly over my devices, don't know why it wasn't working yesterday. Closing this ticket
