### ISSUE TITLE
Make 'Turn Off (Use Firefox..)' option first in the dropdown list

### ISSUE THREAD

**Issue by miopa** [foxyproxy/firefox-extension#78]
When you have a lot of proxies, currently you have to scroll down the list for it, and it's fairly frequent operation for a lot of users

**Comment by ericjung** [comment]
Interesting suggestion. Thank you! I will change it so it's 2nd in the list.

**Comment by miopa** [comment]
Thanks!

**Comment by ericjung** [comment]
fixed in 7.5
