### ISSUE TITLE
I can read the config file locally, and modify it?

### ISSUE THREAD

**Issue by kfel520** [foxyproxy/firefox-extension#79]
Dear: ericjung

One of my Crawler program, need often automatically to modify foxyproxy Settings, I don't know how to do it now.Of course the most simple way is to read the config file

Unfortunately, I can't find it. I need to change the user name and password of the proxy IP address port at any time. Can you tell me how to automatically handle these settings of FoxyProxy?

**Comment by ericjung** [comment]
> Can you tell me how to automatically handle these settings of FoxyProxy?

There is no way to do it after Firefox 57. Before Firefox 57, FoxyProxy had an API you could use to edit settings -- or you could edit the settings file directly.

Now the settings are stored somewhere in the Firefox profile, possibly part of other local storage from other extensions. I don't know. It's not revealed by Mozilla. And if you reverse engineer it, there is no guarantee it won't change by Mozilla.

I am sorry I can't help you. I know it would be useful -- before FoxyProxy used to have this feature.

Closing.
