### ISSUE TITLE
Sync button is hidden until proxy is added

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#83]
From an email sent to me:

> When the extensions is installed in a new Firefox, there is seemingly no way to enable sync without adding a dummy rule. It would be preferable if I could ask it to import these rules without having to adding a meaningless rule first.

Indeed the "You do not have any proxy settings. Please click Add to start." covers the sync button
![Screenshot from 2020-07-08 10-03-46](https://user-images.githubusercontent.com/5875610/86942430-5d70f280-c102-11ea-8776-70092889e74e.png)

**Comment by ericjung** [comment]
fixed in 7.5

**Comment by draidin135730** [comment]
Hi thanx for your good app
