### ISSUE TITLE
extensions.webextensions.remote = false

### ISSUE THREAD

**Issue by rextheleopard** [foxyproxy/firefox-extension#87]
+ Windows x32_64 10.0.20170.1000
+ Mozilla Firefox 80.0a1 (2020-07-20) (64-bit)
+ FoxyProxy Standard 7.5

If **extensions.webextensions.remote** option in firefox set to **false** (needs restart), foxyproxy standard options page does not opens from toolbar icon button.

**Comment by ericjung** [comment]
Out-of-process extensions are not supported by Firefox anymore, and *extensions.webextensions.remote* [is going to be removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1613141), so I'm closing this (WONT FIX).
