### ISSUE TITLE
Unable to add, remove or edit patterns in a proxy

### ISSUE THREAD

**Issue by h4iku** [foxyproxy/firefox-extension#94]
I use FoxyProxy in Firefox with Tor as a SOCKS5 proxy to work around some blocked domains. I'm trying to add a new pattern to this proxy that already has about 140 patterns, but it doesn't save the newly added pattern. I thought I've reached the maximum number of allowed patterns, but then I tried removing a pattern, and it didn't save the removed pattern either. I removed and installed the add-on again, but the problem persisted.

Adding patterns to an empty proxy works fine and saves the changes. I tried exporting patterns and importing them back to a new proxy. The pop-up is shown that some number of patterns are imported. Then I press save, but come back to patterns that are not saved. They reset to their previous state.

Finally, I removed patterns until I had 89 whitelisted patterns, and everything started to work normally. So there is a maximum limit on the number of patterns now?

**Comment by ericjung** [comment]
Hi,

> Then I press save, but come back to patterns that are not saved. They reset to their previous state.

There is no save button after import. What do you mean?

However, there is no maximum pattern limit and never has been. This sounds like a bug. Can you either:

1. Paste the exported settings here (you can remove sensitive info if you want but dont change the patterns -- the less you change the better). If you'd rather email it to me directly, let me know and I can get you my email address.

OR

2. If you want to debug this yourself -- it sounds like there is a Javascript error when you are adding a pattern and also when you are importing -- then please turn on extension debugging in Firefox and use F12 to see errors in the console. (this is what I will do if I can get your exported settings).

Thanks and I'm sorry for the trouble!

eric

**Comment by ericjung** [comment]
p.s. if you have storage sync turned on, you may be running into [Firefox's new limits](https://searchfox.org/mozilla-central/rev/8d55e18875b89cdf2a22a7cba60dc40999c18356/toolkit/components/extensions/schemas/storage.json#314-325). I look forward to your reply.

**Comment by h4iku** [comment]
> There is no save button after import. What do you mean?

I meant the save button on the patterns page after importing the patterns.

> if you have storage sync turned on, you may be running into Firefox's new limits.

Yes, I  think that is the problem. I checked the debugger, and every time I add a new pattern it says

```
Unchecked lastError value: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations. patterns.js:241
    checkOptions moz-extension://4febf520-9476-4325-9911-b9c0c24a9186/scripts/patterns.js:241
```

I can email the settings to you, but I don't think it is needed anymore.

I really appreciate your work, and thanks for looking into this.

**Comment by ericjung** [comment]
@h4iku ok, can you close this ticket then?
