### ISSUE TITLE
Unable to sync or import settings in new firefox installation

### ISSUE THREAD

**Issue by sunng87** [foxyproxy/firefox-extension#95]
First of all, thank you for the awesome addon. I have been your user for more than ten years. In my new Firefox installation, verison 79, FoxyProxy was synced but no configuration is available. When I use import settings, it says the operation was success but configuration is still empty.

I'm getting these errors from debug console:

* Error: mode is set to undefined but no active proxySetting is found with that id. Disabling Due To Error
* Unchecked lastError value: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations. 
* Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

Let me know if you need more information for my case.

**Comment by ericjung** [comment]
@sunng87 hi, it looks like you are affected by this new Firefox "feature":

https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79

This user had same problem:
https://github.com/foxyproxy/firefox-extension/issues/94

But there is no resolution right now except to turn off *Synchronize Settings*.

Sorry about that. I will look into optimizing the use of storage, but that is just a band-aid: there are now hard limits on synchronized storage in Firerfox that you will always hit at some point

**Comment by sunng87** [comment]
Thanks for fast response. 

To be clear, users experiencing this issue you will need to edit your exported json to set `sync` to `false` and import it again.

**Comment by ericjung** [comment]
> users experiencing this issue will need to edit the exported json to set sync to false

Wait, what? Why can't you turn it off here, where it says *Synchronize Settings* ?

![image](https://user-images.githubusercontent.com/5875610/89645572-4fd09900-d877-11ea-8307-5c36f714563e.png)

If that is not working for some reason, I can add logic that tries to prevent the user from adding too much data to the extension with warning messages.

**Comment by sunng87** [comment]
@ericjung because if you turn off the sync toggle and import your settings, the toggle is opened again and nothing really imported.

**Comment by ericjung** [comment]
@sunng87 , are you using Firefox Portable? What version of Firefox and on operating system (so I can try to reproduce this)

**Comment by sunng87** [comment]
@ericjung I'm using Firefox from ArchLinux repo

**Comment by ericjung** [comment]
@sunng87 please open the file you want to import in a text editor. Then remove:

`` "sync": true

usually it is at the end but not always.

Save it and import again. Now "synchronize settings" is not automatically turned on.

**Comment by sunng87** [comment]
@ericjung Thank you! That's exact what I said 

> To be clear, users experiencing this issue will need to edit the exported json to set sync to false and import it again.
