### ISSUE TITLE
Grammar error in Russian translation

### ISSUE THREAD

**Issue by alex0987alex** [foxyproxy/firefox-extension#96]
---
Info
Edition: FoxyProxy Standard
Version: 7.5.1
---

https://i.postimg.cc/jSQJDFgm/1596957125.jpg

"проки" -> "про**к**си"
"отк**о**ючить" -> "отк**л**ючить"

**Comment by sosiska** [comment]
> "отк**о**ючить" -> "отк**л**ючить"
fixed in
https://github.com/foxyproxy/firefox-extension/pull/93

**Comment by ericjung** [comment]
Merged! Thank you.;
