### ISSUE TITLE
Support Dark Theme

### ISSUE THREAD

**Issue by xmha97** [foxyproxy/firefox-extension#98]
Hi, Please support the system-wide dark theme. (like [View Image](https://github.com/bijij/ViewImage) extension)

![Firefox](https://user-images.githubusercontent.com/23485114/87686958-6749c400-c79a-11ea-996e-abf0bbffe6cb.gif)

**Comment by erosman** [comment]
Dark/Light Theme feature is done for [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

**Comment by xmha97** [comment]
Thanks 🙏
How I can download and install it?

**Comment by erosman** [comment]
FoxyProxy v8.0 is currently under development  but expected to be released in 2022.
